/// @description Rain Generator

/*
// WARNING:
//      The effects generated by this object may cause epilepsy.
//      If you are affected by this type of effects, deactivate them.
*/

//Initialize particle system
rain_sys = part_system_create();

//Pause / Resume particles
ind = 1;

//Set the depth
part_system_depth(rain_sys,-8);

//Set particle type
rain = part_type_create();

//Set particle sprite
part_type_sprite(rain, spr_rain, 0, 0, 1);

//Set particle alpha
part_type_alpha1(rain, 0.7);

//Set particle motion
part_type_speed(rain, 7, 15, 0, 0);
part_type_direction(rain, 225, 225, 0, 0);

//Set particle colour
part_type_colour1(rain, c_white);

//Create emitter
emitter = part_emitter_create(rain_sys);

//Set emitter stream
part_emitter_stream(rain_sys,emitter,rain, 5);

//Set emitter region
part_emitter_region(rain_sys,emitter, __view_get( e__VW.XView, 0 )-600, __view_get( e__VW.XView, 0 )+__view_get( e__VW.WView, 0 )+600, 0, 0, ps_shape_line, ps_distr_linear);

//Generate particles
repeat (5)
    part_system_update(rain_sys);

/* */
/*  */
