function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -100; // obj_persistent
	global.__objectDepths[1] = 0; // obj_rainmaker
	global.__objectDepths[2] = 0; // obj_snowmaker
	global.__objectDepths[3] = -5; // obj_discoball
	global.__objectDepths[4] = 0; // obj_bganimator
	global.__objectDepths[5] = 1000000; // obj_levelcontrol
	global.__objectDepths[6] = -9; // obj_levelcontrol_light
	global.__objectDepths[7] = -7; // obj_tilehider
	global.__objectDepths[8] = -7; // obj_gotomap
	global.__objectDepths[9] = 0; // obj_autoscroll
	global.__objectDepths[10] = 0; // obj_autoscroll_modifier
	global.__objectDepths[11] = 0; // obj_guessblock_manager
	global.__objectDepths[12] = 0; // obj_light
	global.__objectDepths[13] = 0; // obj_light_st
	global.__objectDepths[14] = 0; // obj_light_disco
	global.__objectDepths[15] = -5; // obj_player
	global.__objectDepths[16] = -5; // obj_player_warp
	global.__objectDepths[17] = -5; // obj_player_jump
	global.__objectDepths[18] = -5; // obj_player_climb
	global.__objectDepths[19] = -5; // obj_player_rocket
	global.__objectDepths[20] = -2; // obj_solid
	global.__objectDepths[21] = -2; // obj_semisolid
	global.__objectDepths[22] = -1; // obj_climb
	global.__objectDepths[23] = -1; // obj_climb_net
	global.__objectDepths[24] = -2; // obj_swim
	global.__objectDepths[25] = -2; // obj_slippery
	global.__objectDepths[26] = -2; // obj_slope_r
	global.__objectDepths[27] = -2; // obj_slope_l
	global.__objectDepths[28] = -2; // obj_slope_sr
	global.__objectDepths[29] = -2; // obj_slope_sl
	global.__objectDepths[30] = -2; // obj_slope_ice_r
	global.__objectDepths[31] = -2; // obj_slope_ice_l
	global.__objectDepths[32] = -2; // obj_slope_ice_sr
	global.__objectDepths[33] = -2; // obj_slope_ice_sl
	global.__objectDepths[34] = -2; // obj_ceilslope_r
	global.__objectDepths[35] = -2; // obj_ceilslope_l
	global.__objectDepths[36] = -2; // obj_ceilslope_sr
	global.__objectDepths[37] = -2; // obj_ceilslope_sl
	global.__objectDepths[38] = 0; // obj_hurtmask
	global.__objectDepths[39] = 0; // obj_hurtmask_square
	global.__objectDepths[40] = 9; // obj_qblock
	global.__objectDepths[41] = 9; // obj_qblock_scatter
	global.__objectDepths[42] = 9; // obj_qblock_multicoin
	global.__objectDepths[43] = 9; // obj_qblock_multicoin_shroom
	global.__objectDepths[44] = 9; // obj_qblock_hidden
	global.__objectDepths[45] = 9; // obj_qblock_double
	global.__objectDepths[46] = 9; // obj_qblock_double_hidden
	global.__objectDepths[47] = 9; // obj_qblock_triple
	global.__objectDepths[48] = 9; // obj_qblock_triple_hidden
	global.__objectDepths[49] = 9; // obj_qblock_big
	global.__objectDepths[50] = 9; // obj_qblock_p
	global.__objectDepths[51] = -1; // obj_qblock_spiked
	global.__objectDepths[52] = -1; // obj_qblock_winged
	global.__objectDepths[53] = 9; // obj_flowerblock
	global.__objectDepths[54] = 9; // obj_leafblock
	global.__objectDepths[55] = 9; // obj_hammerblock
	global.__objectDepths[56] = 9; // obj_boomerangblock
	global.__objectDepths[57] = 9; // obj_bombblock
	global.__objectDepths[58] = 0; // obj_shellblock
	global.__objectDepths[59] = 9; // obj_boltblock
	global.__objectDepths[60] = 9; // obj_catblock
	global.__objectDepths[61] = 9; // obj_starblock
	global.__objectDepths[62] = 9; // obj_yoshiblock
	global.__objectDepths[63] = 9; // obj_kuriboblock
	global.__objectDepths[64] = 9; // obj_switchblock
	global.__objectDepths[65] = 9; // obj_dashblock
	global.__objectDepths[66] = 9; // obj_onoffblock_y
	global.__objectDepths[67] = 9; // obj_onoffplatform_y
	global.__objectDepths[68] = -1; // obj_onofflift_y
	global.__objectDepths[69] = 9; // obj_onoffblock_g
	global.__objectDepths[70] = 9; // obj_onoffplatform_g
	global.__objectDepths[71] = -1; // obj_onofflift_g
	global.__objectDepths[72] = 9; // obj_onoffblock_r
	global.__objectDepths[73] = 9; // obj_onoffplatform_r
	global.__objectDepths[74] = -1; // obj_onofflift_r
	global.__objectDepths[75] = 9; // obj_onoffblock_b
	global.__objectDepths[76] = 9; // obj_onoffplatform_b
	global.__objectDepths[77] = -1; // obj_onofflift_b
	global.__objectDepths[78] = 9; // obj_brick
	global.__objectDepths[79] = 9; // obj_bigbrick
	global.__objectDepths[80] = 9; // obj_bluebrick
	global.__objectDepths[81] = 9; // obj_redbrick
	global.__objectDepths[82] = 9; // obj_graybrick
	global.__objectDepths[83] = 9; // obj_greenbrick
	global.__objectDepths[84] = 9; // obj_flipblock
	global.__objectDepths[85] = 0; // obj_viewblock
	global.__objectDepths[86] = 9; // obj_noteblock
	global.__objectDepths[87] = 9; // obj_noteblock_hidden
	global.__objectDepths[88] = 9; // obj_noteblock_blue
	global.__objectDepths[89] = 9; // obj_noteblock_blue_hidden
	global.__objectDepths[90] = 9; // obj_noteblock_warp
	global.__objectDepths[91] = 9; // obj_noteblock_warp_hidden
	global.__objectDepths[92] = -1; // obj_noteblock_diagonal_r
	global.__objectDepths[93] = -1; // obj_noteblock_diagonal_l
	global.__objectDepths[94] = 9; // obj_messageblock
	global.__objectDepths[95] = 9; // obj_pswitchblock
	global.__objectDepths[96] = 9; // obj_qswitchblock
	global.__objectDepths[97] = 9; // obj_eswitchblock
	global.__objectDepths[98] = 9; // obj_woodblock
	global.__objectDepths[99] = 9; // obj_eblock
	global.__objectDepths[100] = 9; // obj_pblock
	global.__objectDepths[101] = 9; // obj_area_y
	global.__objectDepths[102] = 9; // obj_area_g
	global.__objectDepths[103] = 9; // obj_area_r
	global.__objectDepths[104] = 9; // obj_area_b
	global.__objectDepths[105] = 9; // obj_arrowblock
	global.__objectDepths[106] = 9; // obj_arrowblock_left
	global.__objectDepths[107] = 9; // obj_arrowblock_right
	global.__objectDepths[108] = 9; // obj_arrowblock_reset
	global.__objectDepths[109] = 9; // obj_discoblock
	global.__objectDepths[110] = -2; // obj_goomba
	global.__objectDepths[111] = -2; // obj_paragoomba
	global.__objectDepths[112] = -2; // obj_goombrat
	global.__objectDepths[113] = -2; // obj_goomba_red
	global.__objectDepths[114] = -2; // obj_paragoomba_red
	global.__objectDepths[115] = -2; // obj_galoomba
	global.__objectDepths[116] = -2; // obj_paragaloomba
	global.__objectDepths[117] = -2; // obj_galoomba_parachute
	global.__objectDepths[118] = -2; // obj_goombud
	global.__objectDepths[119] = -2; // obj_goomba_shoe
	global.__objectDepths[120] = -2; // obj_koopa
	global.__objectDepths[121] = -2; // obj_parakoopa
	global.__objectDepths[122] = -2; // obj_parakoopa_fly
	global.__objectDepths[123] = -2; // obj_beachkoopa
	global.__objectDepths[124] = -2; // obj_koopa_red
	global.__objectDepths[125] = -2; // obj_parakoopa_red
	global.__objectDepths[126] = -2; // obj_beachkoopa_red
	global.__objectDepths[127] = -2; // obj_koopa_blue
	global.__objectDepths[128] = -2; // obj_beachkoopa_blue
	global.__objectDepths[129] = -2; // obj_koopa_yellow
	global.__objectDepths[130] = -2; // obj_parakoopa_yellow
	global.__objectDepths[131] = -2; // obj_beachkoopa_yellow
	global.__objectDepths[132] = -2; // obj_rex
	global.__objectDepths[133] = -2; // obj_rex_red
	global.__objectDepths[134] = -2; // obj_dinotorch
	global.__objectDepths[135] = -2; // obj_dinorhino
	global.__objectDepths[136] = -2; // obj_spike
	global.__objectDepths[137] = -2; // obj_buzzybeetle
	global.__objectDepths[138] = -2; // obj_ceilingbuzzy
	global.__objectDepths[139] = -2; // obj_spiny
	global.__objectDepths[140] = -2; // obj_ceilingspiny
	global.__objectDepths[141] = -2; // obj_pplant
	global.__objectDepths[142] = -2; // obj_pplant_fire
	global.__objectDepths[143] = -2; // obj_pplant_side_r
	global.__objectDepths[144] = -2; // obj_pplant_side_l
	global.__objectDepths[145] = -2; // obj_pplant_fire_side_r
	global.__objectDepths[146] = -2; // obj_pplant_fire_side_l
	global.__objectDepths[147] = -2; // obj_pplant_large
	global.__objectDepths[148] = -2; // obj_pplant_large_down
	global.__objectDepths[149] = -2; // obj_pplant_large_fire
	global.__objectDepths[150] = -2; // obj_pplant_large_fire_down
	global.__objectDepths[151] = -2; // obj_jpplant
	global.__objectDepths[152] = -2; // obj_ptooie
	global.__objectDepths[153] = 0; // obj_ptooie_pipe
	global.__objectDepths[154] = -2; // obj_swooper
	global.__objectDepths[155] = -2; // obj_spiketop
	global.__objectDepths[156] = -2; // obj_spiketop_blue
	global.__objectDepths[157] = -2; // obj_nokobomb
	global.__objectDepths[158] = -2; // obj_nokobombette
	global.__objectDepths[159] = -2; // obj_ceilingnokobombette
	global.__objectDepths[160] = 10; // obj_blargg
	global.__objectDepths[161] = -2; // obj_busterbeetle
	global.__objectDepths[162] = -2; // obj_cheepcheep
	global.__objectDepths[163] = -2; // obj_cheepcheep_jump
	global.__objectDepths[164] = -2; // obj_cheepcheep_green
	global.__objectDepths[165] = -2; // obj_smwcheep
	global.__objectDepths[166] = -2; // obj_smwcheep_v
	global.__objectDepths[167] = -1; // obj_smwcheep_flop
	global.__objectDepths[168] = -2; // obj_bossbass
	global.__objectDepths[169] = -2; // obj_bigbertha
	global.__objectDepths[170] = -2; // obj_blurp
	global.__objectDepths[171] = -2; // obj_ripvanfish
	global.__objectDepths[172] = -2; // obj_porchupuffer
	global.__objectDepths[173] = -2; // obj_urchin
	global.__objectDepths[174] = -2; // obj_urchin_wall
	global.__objectDepths[175] = -2; // obj_dolphin
	global.__objectDepths[176] = -2; // obj_dolphin_jump
	global.__objectDepths[177] = -2; // obj_lavalotus
	global.__objectDepths[178] = 9; // obj_torpedobox
	global.__objectDepths[179] = 9; // obj_jelectro
	global.__objectDepths[180] = -2; // obj_blooper
	global.__objectDepths[181] = -2; // obj_pokey
	global.__objectDepths[182] = -2; // obj_firesnake
	global.__objectDepths[183] = -2; // obj_brickgoomba
	global.__objectDepths[184] = -2; // obj_angrysun
	global.__objectDepths[185] = -2; // obj_hoopster
	global.__objectDepths[186] = -2; // obj_ninji_black
	global.__objectDepths[187] = -2; // obj_fuzzy
	global.__objectDepths[188] = -2; // obj_fuzzy_line
	global.__objectDepths[189] = -2; // obj_wiggler
	global.__objectDepths[190] = -2; // obj_nipper
	global.__objectDepths[191] = -2; // obj_firenipper
	global.__objectDepths[192] = -2; // obj_monty
	global.__objectDepths[193] = -2; // obj_monty_chase
	global.__objectDepths[194] = 8; // obj_monty_dig
	global.__objectDepths[195] = -2; // obj_volcanolotus
	global.__objectDepths[196] = -2; // obj_lakitu
	global.__objectDepths[197] = -2; // obj_lakitu_red
	global.__objectDepths[198] = -2; // obj_pipelakitu
	global.__objectDepths[199] = -2; // obj_pipelakitu_red
	global.__objectDepths[200] = -2; // obj_firechomp
	global.__objectDepths[201] = -2; // obj_parabeetle
	global.__objectDepths[202] = -2; // obj_bigparabeetle
	global.__objectDepths[203] = -2; // obj_foo
	global.__objectDepths[204] = 9; // obj_skewer
	global.__objectDepths[205] = 9; // obj_skewer_up
	global.__objectDepths[206] = 9; // obj_skewer_left
	global.__objectDepths[207] = 9; // obj_skewer_right
	global.__objectDepths[208] = -1; // obj_firebar_manager
	global.__objectDepths[209] = -1; // obj_rotodisc_manager
	global.__objectDepths[210] = -1; // obj_ballnchain_manager
	global.__objectDepths[211] = -1; // obj_laser_manager
	global.__objectDepths[212] = 10; // obj_crusher
	global.__objectDepths[213] = 10; // obj_pencilpillar
	global.__objectDepths[214] = -2; // obj_drybones
	global.__objectDepths[215] = -2; // obj_bonybeetle
	global.__objectDepths[216] = 10; // obj_podoboo
	global.__objectDepths[217] = 10; // obj_podoboo_ceiling
	global.__objectDepths[218] = -2; // obj_thwomp
	global.__objectDepths[219] = -2; // obj_thwomp_left
	global.__objectDepths[220] = -2; // obj_thwomp_right
	global.__objectDepths[221] = -2; // obj_thwomp_diagonal
	global.__objectDepths[222] = -2; // obj_thwimp
	global.__objectDepths[223] = -2; // obj_netkoopa
	global.__objectDepths[224] = -2; // obj_netkoopa_red
	global.__objectDepths[225] = 10; // obj_grinder
	global.__objectDepths[226] = -2; // obj_grinder_line
	global.__objectDepths[227] = -2; // obj_hotfoot
	global.__objectDepths[228] = -2; // obj_lilspark
	global.__objectDepths[229] = -2; // obj_hothead
	global.__objectDepths[230] = -2; // obj_bowserstatue
	global.__objectDepths[231] = -2; // obj_bowserstatue_gold
	global.__objectDepths[232] = -2; // obj_magikoopa
	global.__objectDepths[233] = -2; // obj_fishbone
	global.__objectDepths[234] = -2; // obj_boo
	global.__objectDepths[235] = -2; // obj_bigboo
	global.__objectDepths[236] = -2; // obj_boocircle
	global.__objectDepths[237] = -2; // obj_boosnake
	global.__objectDepths[238] = -2; // obj_booblock
	global.__objectDepths[239] = -2; // obj_boostretch
	global.__objectDepths[240] = -2; // obj_boostretch_ceiling
	global.__objectDepths[241] = -1; // obj_peepa_manager
	global.__objectDepths[242] = -2; // obj_peepa
	global.__objectDepths[243] = -2; // obj_peepa_v
	global.__objectDepths[244] = -2; // obj_eerie
	global.__objectDepths[245] = -2; // obj_bobomb
	global.__objectDepths[246] = -2; // obj_bobomb_parachute
	global.__objectDepths[247] = -2; // obj_mechakoopa
	global.__objectDepths[248] = -2; // obj_bulletbill
	global.__objectDepths[249] = -2; // obj_missilebill
	global.__objectDepths[250] = -2; // obj_banzaibill
	global.__objectDepths[251] = -2; // obj_banzaiblaster
	global.__objectDepths[252] = 9; // obj_cannon
	global.__objectDepths[253] = 9; // obj_cannon_side
	global.__objectDepths[254] = 9; // obj_cannon_quad
	global.__objectDepths[255] = -2; // obj_cannon_big
	global.__objectDepths[256] = 0; // obj_cannon_spike
	global.__objectDepths[257] = -2; // obj_engine
	global.__objectDepths[258] = -2; // obj_engine_alt
	global.__objectDepths[259] = -2; // obj_rockywrench
	global.__objectDepths[260] = -2; // obj_shyguy
	global.__objectDepths[261] = -2; // obj_shyguy_big
	global.__objectDepths[262] = -2; // obj_shyguy_b
	global.__objectDepths[263] = -2; // obj_shyguy_big_b
	global.__objectDepths[264] = -2; // obj_shyguy_p
	global.__objectDepths[265] = -2; // obj_snifit
	global.__objectDepths[266] = -2; // obj_snifit_b
	global.__objectDepths[267] = -2; // obj_snifit_g
	global.__objectDepths[268] = -2; // obj_snifit_p
	global.__objectDepths[269] = -2; // obj_ninji
	global.__objectDepths[270] = -2; // obj_ninji_chase
	global.__objectDepths[271] = -2; // obj_ninji_big
	global.__objectDepths[272] = -2; // obj_tweeter
	global.__objectDepths[273] = -2; // obj_tweeter_b
	global.__objectDepths[274] = -2; // obj_hoopster_red
	global.__objectDepths[275] = -2; // obj_bombguy
	global.__objectDepths[276] = -2; // obj_cobrat
	global.__objectDepths[277] = -2; // obj_cobrat_jar
	global.__objectDepths[278] = -2; // obj_flurry
	global.__objectDepths[279] = -2; // obj_beezo
	global.__objectDepths[280] = -2; // obj_phanto
	global.__objectDepths[281] = -2; // obj_panser
	global.__objectDepths[282] = -2; // obj_panser_g
	global.__objectDepths[283] = -2; // obj_panser_b
	global.__objectDepths[284] = -2; // obj_panser_p
	global.__objectDepths[285] = -2; // obj_pokey_green
	global.__objectDepths[286] = -2; // obj_porcupo
	global.__objectDepths[287] = -2; // obj_porcupo_r
	global.__objectDepths[288] = -2; // obj_autobomb
	global.__objectDepths[289] = -2; // obj_trouter
	global.__objectDepths[290] = -2; // obj_goomba_big
	global.__objectDepths[291] = -2; // obj_koopa_big
	global.__objectDepths[292] = -2; // obj_parakoopa_big
	global.__objectDepths[293] = -2; // obj_parakoopa_big_fly
	global.__objectDepths[294] = -2; // obj_koopa_big_red
	global.__objectDepths[295] = -2; // obj_parakoopa_big_red
	global.__objectDepths[296] = -2; // obj_bigplant
	global.__objectDepths[297] = -2; // obj_megamole
	global.__objectDepths[298] = -2; // obj_bossorb
	global.__objectDepths[299] = 9; // obj_bossdoor
	global.__objectDepths[300] = -2; // obj_boomboom
	global.__objectDepths[301] = -2; // obj_generator_galoomba
	global.__objectDepths[302] = -2; // obj_generator_cheepcheep
	global.__objectDepths[303] = -2; // obj_generator_spikedcheep
	global.__objectDepths[304] = -2; // obj_generator_spikedcheep_b
	global.__objectDepths[305] = -2; // obj_generator_dolphin
	global.__objectDepths[306] = -2; // obj_generator_eerie
	global.__objectDepths[307] = -2; // obj_generator_bobomb
	global.__objectDepths[308] = -2; // obj_generator_bulletbill
	global.__objectDepths[309] = -2; // obj_generator_beezo
	global.__objectDepths[310] = -2; // obj_generator_enemy
	global.__objectDepths[311] = -2; // obj_hammerbro
	global.__objectDepths[312] = -2; // obj_boomerangbro
	global.__objectDepths[313] = -2; // obj_firebro
	global.__objectDepths[314] = -2; // obj_icebro
	global.__objectDepths[315] = -2; // obj_sledgebro
	global.__objectDepths[316] = -2; // obj_afhb
	global.__objectDepths[317] = -2; // obj_sumobro
	global.__objectDepths[318] = -2; // obj_walrus
	global.__objectDepths[319] = -2; // obj_pararus
	global.__objectDepths[320] = -2; // obj_grayrus
	global.__objectDepths[321] = -2; // obj_gladrus
	global.__objectDepths[322] = 9; // obj_chainchomp
	global.__objectDepths[323] = -2; // obj_charginchuck
	global.__objectDepths[324] = -2; // obj_clappinchuck
	global.__objectDepths[325] = 0; // obj_holdbubble_enemy
	global.__objectDepths[326] = -10; // obj_mapcontrol
	global.__objectDepths[327] = -5; // obj_mapplayer
	global.__objectDepths[328] = 8; // obj_mapbridge_h
	global.__objectDepths[329] = 7; // obj_mapbridge_v
	global.__objectDepths[330] = 8; // obj_mappath_ladder
	global.__objectDepths[331] = 8; // obj_mappath_beanstalk
	global.__objectDepths[332] = 0; // obj_mappath_h
	global.__objectDepths[333] = 8; // obj_mappath_v
	global.__objectDepths[334] = 8; // obj_mappath_up
	global.__objectDepths[335] = 8; // obj_mappath_down
	global.__objectDepths[336] = 8; // obj_mappath_left
	global.__objectDepths[337] = 8; // obj_mappath_right
	global.__objectDepths[338] = 8; // obj_mappath_upleft
	global.__objectDepths[339] = 8; // obj_mappath_upright
	global.__objectDepths[340] = 8; // obj_mappath_downleft
	global.__objectDepths[341] = 8; // obj_mappath_downright
	global.__objectDepths[342] = 8; // obj_mappath_levelnode
	global.__objectDepths[343] = 8; // obj_mappath_emptynode
	global.__objectDepths[344] = 7; // obj_mappath_water
	global.__objectDepths[345] = 1; // obj_maplevel_switch_y
	global.__objectDepths[346] = 1; // obj_maplevel_switch_g
	global.__objectDepths[347] = 1; // obj_maplevel_switch_r
	global.__objectDepths[348] = 1; // obj_maplevel_switch_b
	global.__objectDepths[349] = 1; // obj_mappanel_house
	global.__objectDepths[350] = 1; // obj_mappanel_house_b
	global.__objectDepths[351] = 1; // obj_mappanel_house_c
	global.__objectDepths[352] = 8; // obj_mapstart
	global.__objectDepths[353] = 1; // obj_maplevel
	global.__objectDepths[354] = 1; // obj_maplevel_pipe
	global.__objectDepths[355] = 1; // obj_maplevel_pipe2
	global.__objectDepths[356] = 1; // obj_maplevel_ghost
	global.__objectDepths[357] = 1; // obj_maplevel_castle
	global.__objectDepths[358] = 10; // obj_mapwater
	global.__objectDepths[359] = 10; // obj_maplava
	global.__objectDepths[360] = 2; // obj_maptree
	global.__objectDepths[361] = 2; // obj_maptree_alt
	global.__objectDepths[362] = 2; // obj_maptree_alt_b
	global.__objectDepths[363] = 2; // obj_maphill
	global.__objectDepths[364] = 2; // obj_maphilltrio
	global.__objectDepths[365] = 2; // obj_mapfire
	global.__objectDepths[366] = 0; // obj_modifier
	global.__objectDepths[367] = -5; // obj_modifier_music
	global.__objectDepths[368] = 8; // obj_muncher
	global.__objectDepths[369] = 8; // obj_muncher_pipe
	global.__objectDepths[370] = 8; // obj_muncher_pipe2
	global.__objectDepths[371] = 12; // obj_watertop
	global.__objectDepths[372] = 12; // obj_waterfall
	global.__objectDepths[373] = 12; // obj_waterfall_noswim
	global.__objectDepths[374] = -1; // obj_tides
	global.__objectDepths[375] = 9; // obj_ilavaslope_l
	global.__objectDepths[376] = 9; // obj_ilavaslope_r
	global.__objectDepths[377] = 9; // obj_ilavaslope_sl
	global.__objectDepths[378] = 9; // obj_ilavaslope_sr
	global.__objectDepths[379] = 9; // obj_lavacorner_a
	global.__objectDepths[380] = 9; // obj_lavacorner_b
	global.__objectDepths[381] = 9; // obj_lavacorner_c
	global.__objectDepths[382] = 9; // obj_lavacorner_d
	global.__objectDepths[383] = 9; // obj_lavaedge_a
	global.__objectDepths[384] = 9; // obj_lavaedge_b
	global.__objectDepths[385] = 9; // obj_lavaedge_c
	global.__objectDepths[386] = 9; // obj_lavaedge_d
	global.__objectDepths[387] = -6; // obj_lavaslope_l
	global.__objectDepths[388] = -6; // obj_lavaslope_r
	global.__objectDepths[389] = -6; // obj_lavaslope_sl
	global.__objectDepths[390] = -6; // obj_lavaslope_sr
	global.__objectDepths[391] = 9; // obj_lava_top
	global.__objectDepths[392] = 9; // obj_lava_ceiling
	global.__objectDepths[393] = 9; // obj_lava
	global.__objectDepths[394] = 9; // obj_lava_b
	global.__objectDepths[395] = 9; // obj_lava_c
	global.__objectDepths[396] = 9; // obj_lava_d
	global.__objectDepths[397] = 12; // obj_lavafall
	global.__objectDepths[398] = 11; // obj_vine
	global.__objectDepths[399] = 8; // obj_signpost
	global.__objectDepths[400] = 11; // obj_seaweed
	global.__objectDepths[401] = -6; // obj_quicksand
	global.__objectDepths[402] = -2; // obj_mushroom
	global.__objectDepths[403] = -2; // obj_fireflower
	global.__objectDepths[404] = -2; // obj_iceflower
	global.__objectDepths[405] = -2; // obj_carrot
	global.__objectDepths[406] = -2; // obj_leaf
	global.__objectDepths[407] = -2; // obj_frogsuit
	global.__objectDepths[408] = -2; // obj_tanookisuit
	global.__objectDepths[409] = -2; // obj_hammerflower
	global.__objectDepths[410] = -2; // obj_boomerangflower
	global.__objectDepths[411] = -2; // obj_superflower
	global.__objectDepths[412] = -2; // obj_bombshroom
	global.__objectDepths[413] = -2; // obj_blueshell
	global.__objectDepths[414] = -2; // obj_beeshroom
	global.__objectDepths[415] = -2; // obj_voltshroom
	global.__objectDepths[416] = -2; // obj_penguinsuit
	global.__objectDepths[417] = -2; // obj_propellershroom
	global.__objectDepths[418] = 10; // obj_superbell
	global.__objectDepths[419] = -2; // obj_helmet
	global.__objectDepths[420] = -2; // obj_starman
	global.__objectDepths[421] = -2; // obj_pwing
	global.__objectDepths[422] = -2; // obj_1up
	global.__objectDepths[423] = -2; // obj_poison
	global.__objectDepths[424] = -2; // obj_rotten
	global.__objectDepths[425] = -2; // obj_goldshroom
	global.__objectDepths[426] = -1; // obj_1up_h1
	global.__objectDepths[427] = -1; // obj_1up_h2
	global.__objectDepths[428] = -1; // obj_1up_h3
	global.__objectDepths[429] = -1; // obj_1up_h4
	global.__objectDepths[430] = -1; // obj_redring
	global.__objectDepths[431] = -1; // obj_yellowring
	global.__objectDepths[432] = 9; // obj_coin
	global.__objectDepths[433] = 9; // obj_coin_p
	global.__objectDepths[434] = 9; // obj_coin_r
	global.__objectDepths[435] = 9; // obj_acecoin
	global.__objectDepths[436] = 9; // obj_starcoin
	global.__objectDepths[437] = 11; // obj_berry
	global.__objectDepths[438] = 11; // obj_berry_g
	global.__objectDepths[439] = 0; // obj_holdbubble
	global.__objectDepths[440] = -2; // obj_plusclock_10
	global.__objectDepths[441] = -2; // obj_plusclock_50
	global.__objectDepths[442] = 9; // obj_icecoin
	global.__objectDepths[443] = 9; // obj_iceplant
	global.__objectDepths[444] = 9; // obj_3upmoon
	global.__objectDepths[445] = 9; // obj_path
	global.__objectDepths[446] = 11; // obj_path_hor
	global.__objectDepths[447] = 11; // obj_path_ver
	global.__objectDepths[448] = 11; // obj_path_diagonal_r
	global.__objectDepths[449] = 11; // obj_path_diagonal_l
	global.__objectDepths[450] = 11; // obj_path_circle_a1
	global.__objectDepths[451] = 11; // obj_path_circle_a2
	global.__objectDepths[452] = 11; // obj_path_circle_a3
	global.__objectDepths[453] = 11; // obj_path_circle_a4
	global.__objectDepths[454] = 11; // obj_path_circle_b1
	global.__objectDepths[455] = 11; // obj_path_circle_b2
	global.__objectDepths[456] = 11; // obj_path_circle_b3
	global.__objectDepths[457] = 11; // obj_path_circle_b4
	global.__objectDepths[458] = -1; // obj_platform
	global.__objectDepths[459] = -1; // obj_platform_touch
	global.__objectDepths[460] = -1; // obj_platform_floating
	global.__objectDepths[461] = -1; // obj_platform_falling
	global.__objectDepths[462] = -2; // obj_generator_log
	global.__objectDepths[463] = -1; // obj_carrotlift
	global.__objectDepths[464] = -1; // obj_carrotlift_32x
	global.__objectDepths[465] = 9; // obj_arrowplatform
	global.__objectDepths[466] = -1; // obj_rotaryplatform
	global.__objectDepths[467] = -1; // obj_boltlift
	global.__objectDepths[468] = -1; // obj_donut
	global.__objectDepths[469] = -1; // obj_donut_triple
	global.__objectDepths[470] = -1; // obj_donut_red
	global.__objectDepths[471] = -1; // obj_donut_red_triple
	global.__objectDepths[472] = 0; // obj_ferrisplatform
	global.__objectDepths[473] = 0; // obj_ferrisplatform_2x
	global.__objectDepths[474] = 0; // obj_ferrisplatform_3x
	global.__objectDepths[475] = 0; // obj_balanceplatform
	global.__objectDepths[476] = -1; // obj_accordion_h
	global.__objectDepths[477] = -1; // obj_accordion_v
	global.__objectDepths[478] = -1; // obj_accordion_hv
	global.__objectDepths[479] = -1; // obj_blocktrain
	global.__objectDepths[480] = -1; // obj_stoneblock
	global.__objectDepths[481] = -1; // obj_timedplatform
	global.__objectDepths[482] = -1; // obj_slopeplatform_r
	global.__objectDepths[483] = -1; // obj_slopeplatform_l
	global.__objectDepths[484] = 16; // obj_weightplatform
	global.__objectDepths[485] = -1; // obj_movingrope
	global.__objectDepths[486] = -1; // obj_movingsaw
	global.__objectDepths[487] = 10; // obj_movingpipe
	global.__objectDepths[488] = 10; // obj_skullraft
	global.__objectDepths[489] = 9; // obj_conveyor_l
	global.__objectDepths[490] = 9; // obj_conveyor_r
	global.__objectDepths[491] = -1; // obj_yoshiplatform
	global.__objectDepths[492] = -1; // obj_pulleyplatform
	global.__objectDepths[493] = 12; // obj_mushroomplatform
	global.__objectDepths[494] = -1; // obj_jellyplatform
	global.__objectDepths[495] = 9; // obj_flagpole
	global.__objectDepths[496] = 9; // obj_flagpole_secret
	global.__objectDepths[497] = 0; // obj_incastle
	global.__objectDepths[498] = 9; // obj_crystal
	global.__objectDepths[499] = 9; // obj_crystal_red
	global.__objectDepths[500] = -2; // obj_hawkmouth
	global.__objectDepths[501] = -2; // obj_hawkmouth_secret
	global.__objectDepths[502] = -2; // obj_goalcard
	global.__objectDepths[503] = -2; // obj_goalcard_secret
	global.__objectDepths[504] = 9; // obj_goalgate
	global.__objectDepths[505] = 9; // obj_goalgate_secret
	global.__objectDepths[506] = 9; // obj_keyhole
	global.__objectDepths[507] = 9; // obj_checkpoint
	global.__objectDepths[508] = 9; // obj_midwaygate
	global.__objectDepths[509] = 8; // obj_midwaygate_tape
	global.__objectDepths[510] = -2; // obj_pswitch
	global.__objectDepths[511] = -2; // obj_gswitch
	global.__objectDepths[512] = -2; // obj_trampoline
	global.__objectDepths[513] = 0; // obj_trampoline_p
	global.__objectDepths[514] = -2; // obj_trampoline_timed
	global.__objectDepths[515] = 9; // obj_barrel
	global.__objectDepths[516] = 9; // obj_barrel_tnt
	global.__objectDepths[517] = -2; // obj_billygun
	global.__objectDepths[518] = -2; // obj_pipeypipe
	global.__objectDepths[519] = -1; // obj_bumper
	global.__objectDepths[520] = -1; // obj_wallspring
	global.__objectDepths[521] = -1; // obj_flipper_top
	global.__objectDepths[522] = -1; // obj_flipper_bottom
	global.__objectDepths[523] = -1; // obj_flipper_left
	global.__objectDepths[524] = -1; // obj_flipper_right
	global.__objectDepths[525] = -2; // obj_blowpipe
	global.__objectDepths[526] = 9; // obj_walltriangle_r
	global.__objectDepths[527] = 9; // obj_walltriangle_l
	global.__objectDepths[528] = 9; // obj_walltriangle_ir
	global.__objectDepths[529] = 9; // obj_walltriangle_il
	global.__objectDepths[530] = -2; // obj_lightblock
	global.__objectDepths[531] = 9; // obj_propellerblock
	global.__objectDepths[532] = -2; // obj_boomerang_blue
	global.__objectDepths[533] = 10; // obj_waterbubble
	global.__objectDepths[534] = -2; // obj_twister
	global.__objectDepths[535] = 9; // obj_pullkey
	global.__objectDepths[536] = -1; // obj_heart
	global.__objectDepths[537] = -1; // obj_cherry
	global.__objectDepths[538] = 9; // obj_vegshroom
	global.__objectDepths[539] = 9; // obj_vegshroom_1up
	global.__objectDepths[540] = 9; // obj_basket
	global.__objectDepths[541] = 9; // obj_grass_coin
	global.__objectDepths[542] = 9; // obj_grass_multicoin
	global.__objectDepths[543] = 9; // obj_grass_sprout
	global.__objectDepths[544] = 9; // obj_grass_pow
	global.__objectDepths[545] = 9; // obj_grass_pow_large
	global.__objectDepths[546] = 9; // obj_grass_bomb
	global.__objectDepths[547] = 9; // obj_grass_shell
	global.__objectDepths[548] = 9; // obj_grass
	global.__objectDepths[549] = 9; // obj_grass_mini
	global.__objectDepths[550] = 9; // obj_grass_large
	global.__objectDepths[551] = 9; // obj_grass_rocket
	global.__objectDepths[552] = 9; // obj_mblock
	global.__objectDepths[553] = 9; // obj_powblock
	global.__objectDepths[554] = 0; // obj_itembubble
	global.__objectDepths[555] = 9; // obj_digsand
	global.__objectDepths[556] = -2; // obj_key
	global.__objectDepths[557] = -2; // obj_key_timed
	global.__objectDepths[558] = -1; // obj_keygate
	global.__objectDepths[559] = 1; // obj_door
	global.__objectDepths[560] = 1; // obj_door_p
	global.__objectDepths[561] = 9; // obj_pipecorner_dr
	global.__objectDepths[562] = 9; // obj_pipecorner_dl
	global.__objectDepths[563] = 9; // obj_pipecorner_ur
	global.__objectDepths[564] = 9; // obj_pipecorner_ul
	global.__objectDepths[565] = -6; // obj_warptop
	global.__objectDepths[566] = -6; // obj_warpbottom
	global.__objectDepths[567] = -6; // obj_warpleft
	global.__objectDepths[568] = -6; // obj_warpright
	global.__objectDepths[569] = -2; // obj_warpmap
	global.__objectDepths[570] = -2; // obj_warppost
	global.__objectDepths[571] = -2; // obj_warproom
	global.__objectDepths[572] = -2; // obj_warpbranch
	global.__objectDepths[573] = -2; // obj_warpcannon
	global.__objectDepths[574] = -2; // obj_warpcannon_big
	global.__objectDepths[575] = -2; // obj_pitwarp
	global.__objectDepths[576] = 0; // obj_pipemanager
	global.__objectDepths[577] = -1; // obj_diggame_block
	global.__objectDepths[578] = -2; // obj_diggame_chest
	global.__objectDepths[579] = 0; // obj_diggame_warptomap
	global.__objectDepths[580] = 1; // obj_toad_slot
	global.__objectDepths[581] = 0; // obj_slotblock
	global.__objectDepths[582] = 0; // obj_slotblock_manager
	global.__objectDepths[583] = 1; // obj_toad
	global.__objectDepths[584] = 1; // obj_chest
	global.__objectDepths[585] = -10; // obj_palacemsg
	global.__objectDepths[586] = 9; // obj_palaceswitch
	global.__objectDepths[587] = -1; // obj_parpull
	global.__objectDepths[588] = -6; // obj_parcarry
	global.__objectDepths[589] = -2; // obj_parhold
	global.__objectDepths[590] = 0; // obj_enemyparent
	global.__objectDepths[591] = -2; // obj_enemyparent_held
	global.__objectDepths[592] = 0; // obj_deactenemyparent
	global.__objectDepths[593] = -2; // obj_subconenemyparent
	global.__objectDepths[594] = -2; // obj_bossparent
	global.__objectDepths[595] = 0; // obj_physicsparent
	global.__objectDepths[596] = 0; // obj_powerupparent
	global.__objectDepths[597] = 0; // obj_projectileparent
	global.__objectDepths[598] = -5; // obj_playerparent
	global.__objectDepths[599] = -5; // obj_playerparent_clear
	global.__objectDepths[600] = -2; // obj_enemytop
	global.__objectDepths[601] = 0; // obj_platformparent
	global.__objectDepths[602] = -2; // obj_slopeparent
	global.__objectDepths[603] = -2; // obj_ceilslopeparent
	global.__objectDepths[604] = 0; // obj_mappathparent
	global.__objectDepths[605] = 0; // obj_maplevelparent
	global.__objectDepths[606] = 0; // obj_pathparent
	global.__objectDepths[607] = -1; // obj_blockparent
	global.__objectDepths[608] = 9; // obj_grayblockparent
	global.__objectDepths[609] = 0; // obj_lightparent
	global.__objectDepths[610] = 0; // obj_deactivateparent
	global.__objectDepths[611] = -5; // obj_mario
	global.__objectDepths[612] = -5; // obj_player_goal_smb1
	global.__objectDepths[613] = 10; // obj_player_goal_smb2
	global.__objectDepths[614] = -5; // obj_player_goal_smb3
	global.__objectDepths[615] = -5; // obj_player_goal_smw
	global.__objectDepths[616] = -5; // obj_player_warpnote
	global.__objectDepths[617] = -7; // obj_player_transform
	global.__objectDepths[618] = -5; // obj_player_rocket2
	global.__objectDepths[619] = -5; // obj_player_eaten
	global.__objectDepths[620] = -5; // obj_player_dead
	global.__objectDepths[621] = -5; // obj_player_door
	global.__objectDepths[622] = -5; // obj_puller
	global.__objectDepths[623] = -5; // obj_statue
	global.__objectDepths[624] = -5; // obj_spinner
	global.__objectDepths[625] = -5; // obj_dropdown
	global.__objectDepths[626] = -5; // obj_wallrunner
	global.__objectDepths[627] = -6; // obj_marker_head
	global.__objectDepths[628] = -6; // obj_marker_bottom
	global.__objectDepths[629] = 9; // obj_emptyblock
	global.__objectDepths[630] = -2; // obj_blockcoin
	global.__objectDepths[631] = -2; // obj_blockcoin2
	global.__objectDepths[632] = 10; // obj_beanstalk
	global.__objectDepths[633] = -2; // obj_bluebrick_th
	global.__objectDepths[634] = 9; // obj_flipblock_flip
	global.__objectDepths[635] = -1; // obj_shard
	global.__objectDepths[636] = -1; // obj_shard_th
	global.__objectDepths[637] = -1; // obj_shard_switch
	global.__objectDepths[638] = 9; // obj_guessblock
	global.__objectDepths[639] = -7; // obj_enemy_dead
	global.__objectDepths[640] = 0; // obj_enemy_multidead
	global.__objectDepths[641] = -7; // obj_enemy_stomped
	global.__objectDepths[642] = -6; // obj_enemy_carried
	global.__objectDepths[643] = 0; // obj_enemy_tick
	global.__objectDepths[644] = -2; // obj_enemy_coin
	global.__objectDepths[645] = -2; // obj_enemy_score
	global.__objectDepths[646] = -2; // obj_stomped
	global.__objectDepths[647] = -6; // obj_goomba_micro
	global.__objectDepths[648] = -2; // obj_galoomba_down
	global.__objectDepths[649] = -2; // obj_koopa_kamikaze
	global.__objectDepths[650] = -4; // obj_dinotorch_fire
	global.__objectDepths[651] = -3; // obj_spike_ball
	global.__objectDepths[652] = -2; // obj_plantfire
	global.__objectDepths[653] = -2; // obj_plantfire2
	global.__objectDepths[654] = -2; // obj_plantball
	global.__objectDepths[655] = -2; // obj_nokobomb_down
	global.__objectDepths[656] = 10; // obj_blargg_jump
	global.__objectDepths[657] = -1; // obj_busterpickup
	global.__objectDepths[658] = -2; // obj_generatorcheep
	global.__objectDepths[659] = -2; // obj_generatorcheep2
	global.__objectDepths[660] = -2; // obj_generatorcheep2b
	global.__objectDepths[661] = -2; // obj_bigbertha_cheep
	global.__objectDepths[662] = -2; // obj_generatordolphin
	global.__objectDepths[663] = -2; // obj_lavalotus_ball
	global.__objectDepths[664] = -2; // obj_torpedoted
	global.__objectDepths[665] = -7; // obj_pokey_dead
	global.__objectDepths[666] = -2; // obj_monty_jump
	global.__objectDepths[667] = -4; // obj_lotusball
	global.__objectDepths[668] = -2; // obj_firesnake_body
	global.__objectDepths[669] = 0; // obj_angrysun_movement
	global.__objectDepths[670] = 0; // obj_wiggler_body
	global.__objectDepths[671] = 0; // obj_lakitu_movement
	global.__objectDepths[672] = -2; // obj_lakitu_egg
	global.__objectDepths[673] = -2; // obj_firechomp_fire
	global.__objectDepths[674] = -6; // obj_foo_fog
	global.__objectDepths[675] = 10; // obj_skewer_trunk
	global.__objectDepths[676] = 10; // obj_skewer_trunk_up
	global.__objectDepths[677] = 10; // obj_skewer_trunk_left
	global.__objectDepths[678] = 10; // obj_skewer_trunk_right
	global.__objectDepths[679] = -2; // obj_firebar
	global.__objectDepths[680] = -2; // obj_rotodisc
	global.__objectDepths[681] = -1; // obj_rotodisc_trail
	global.__objectDepths[682] = -2; // obj_chain
	global.__objectDepths[683] = -2; // obj_ball
	global.__objectDepths[684] = -2; // obj_laser
	global.__objectDepths[685] = -2; // obj_crumblebones
	global.__objectDepths[686] = -2; // obj_boocircle_boo
	global.__objectDepths[687] = 1; // obj_boosnake_trail
	global.__objectDepths[688] = -2; // obj_peepa_b
	global.__objectDepths[689] = -2; // obj_eerie_active
	global.__objectDepths[690] = -2; // obj_bowserstatue_fire
	global.__objectDepths[691] = -1; // obj_magic
	global.__objectDepths[692] = -2; // obj_bobomb_down
	global.__objectDepths[693] = -2; // obj_mechakoopa_down
	global.__objectDepths[694] = 10; // obj_bullet
	global.__objectDepths[695] = 10; // obj_bullet_homing
	global.__objectDepths[696] = 11; // obj_bullet_banzai
	global.__objectDepths[697] = -2; // obj_cannonball
	global.__objectDepths[698] = -2; // obj_cannonball_large
	global.__objectDepths[699] = 10; // obj_cannonball_spike
	global.__objectDepths[700] = 10; // obj_cannonball_spike_trail
	global.__objectDepths[701] = -2; // obj_wrench
	global.__objectDepths[702] = -2; // obj_snifit_ball
	global.__objectDepths[703] = -2; // obj_beezo_active
	global.__objectDepths[704] = -2; // obj_panser_fire
	global.__objectDepths[705] = -2; // obj_autobomb_shyguy
	global.__objectDepths[706] = -2; // obj_autobomb_fire
	global.__objectDepths[707] = -1; // obj_shell
	global.__objectDepths[708] = -1; // obj_shell_kick
	global.__objectDepths[709] = -3; // obj_hammerbro_hammer
	global.__objectDepths[710] = -3; // obj_boomerangbro_boomerang
	global.__objectDepths[711] = -3; // obj_firebro_fireball
	global.__objectDepths[712] = -3; // obj_icebro_snowball
	global.__objectDepths[713] = -2; // obj_afhb_rider
	global.__objectDepths[714] = -2; // obj_sumobro_flame
	global.__objectDepths[715] = -2; // obj_sumobro_lightning
	global.__objectDepths[716] = -2; // obj_chomp
	global.__objectDepths[717] = -1; // obj_chomp_chain
	global.__objectDepths[718] = 0; // obj_holdbubble_enemy_respawn
	global.__objectDepths[719] = -1; // obj_mapghost
	global.__objectDepths[720] = -2; // obj_opener
	global.__objectDepths[721] = -6; // obj_mapcloud
	global.__objectDepths[722] = 9; // obj_coin_m
	global.__objectDepths[723] = 10; // obj_pickup_leaf
	global.__objectDepths[724] = 10; // obj_pickup_pwing
	global.__objectDepths[725] = 10; // obj_pickup_propeller
	global.__objectDepths[726] = -2; // obj_egg
	global.__objectDepths[727] = -2; // obj_egg_pow
	global.__objectDepths[728] = -2; // obj_egg_hatch
	global.__objectDepths[729] = -5; // obj_yoshi
	global.__objectDepths[730] = -2; // obj_yoshi_runaway
	global.__objectDepths[731] = -2; // obj_yoshi_abandon
	global.__objectDepths[732] = -2; // obj_yoshi_fire
	global.__objectDepths[733] = -4; // obj_tongue
	global.__objectDepths[734] = -2; // obj_getshoe
	global.__objectDepths[735] = -5; // obj_kuriboshoe
	global.__objectDepths[736] = -6; // obj_kuriboshoe_lost
	global.__objectDepths[737] = 0; // obj_kuriboshoe_movement
	global.__objectDepths[738] = 0; // obj_stomp
	global.__objectDepths[739] = 10; // obj_powerupsprout
	global.__objectDepths[740] = -11; // obj_powerupprize
	global.__objectDepths[741] = -12; // obj_powerupget
	global.__objectDepths[742] = -12; // obj_reserveitem
	global.__objectDepths[743] = -2; // obj_fireball
	global.__objectDepths[744] = -2; // obj_iceball
	global.__objectDepths[745] = -2; // obj_hammer
	global.__objectDepths[746] = -2; // obj_boomerang
	global.__objectDepths[747] = -2; // obj_superball
	global.__objectDepths[748] = -2; // obj_bomb
	global.__objectDepths[749] = -2; // obj_bolt
	global.__objectDepths[750] = -2; // obj_football
	global.__objectDepths[751] = -6; // obj_invincibility
	global.__objectDepths[752] = 0; // obj_coinchange
	global.__objectDepths[753] = 0; // obj_holdbubble_respawn
	global.__objectDepths[754] = 13; // obj_log
	global.__objectDepths[755] = -1; // obj_arrowplatform_platform
	global.__objectDepths[756] = 0; // obj_spinmask
	global.__objectDepths[757] = 0; // obj_spincollision
	global.__objectDepths[758] = 0; // obj_boltlift_top
	global.__objectDepths[759] = 0; // obj_boltlift_fall
	global.__objectDepths[760] = -1; // obj_ferrisplatform_platform
	global.__objectDepths[761] = -1; // obj_balanceplatform_platform
	global.__objectDepths[762] = 0; // obj_expandplatblock
	global.__objectDepths[763] = -1; // obj_blocktrain_front
	global.__objectDepths[764] = 1; // obj_blocktrain_middle
	global.__objectDepths[765] = -1; // obj_blocktrain_back
	global.__objectDepths[766] = 0; // obj_blocktrain_killer
	global.__objectDepths[767] = 16; // obj_weightplatform_right
	global.__objectDepths[768] = 0; // obj_rope
	global.__objectDepths[769] = 0; // obj_saw
	global.__objectDepths[770] = -1; // obj_pulleyplatform_right
	global.__objectDepths[771] = 12; // obj_pulleyplatform_rope
	global.__objectDepths[772] = 8; // obj_flag
	global.__objectDepths[773] = 8; // obj_flag_p
	global.__objectDepths[774] = 8; // obj_flag_da
	global.__objectDepths[775] = -5; // obj_goalcard_get
	global.__objectDepths[776] = -4; // obj_fadegoal
	global.__objectDepths[777] = -11; // obj_curtaingoal
	global.__objectDepths[778] = 8; // obj_goalgate_tape
	global.__objectDepths[779] = -5; // obj_goalgate_tape_b
	global.__objectDepths[780] = -6; // obj_goalgate_front
	global.__objectDepths[781] = -6; // obj_midwaygate_b
	global.__objectDepths[782] = -2; // obj_trampoline_p_active
	global.__objectDepths[783] = -6; // obj_barrel_up
	global.__objectDepths[784] = -1; // obj_billy
	global.__objectDepths[785] = -6; // obj_billy_dead
	global.__objectDepths[786] = -2; // obj_pipeypipe_plant
	global.__objectDepths[787] = -6; // obj_propellerblock_up
	global.__objectDepths[788] = -2; // obj_boomerang_blue_up
	global.__objectDepths[789] = -6; // obj_twister_bubble
	global.__objectDepths[790] = -10; // obj_turnip_out
	global.__objectDepths[791] = -2; // obj_sorcerer
	global.__objectDepths[792] = -6; // obj_pullkey_up
	global.__objectDepths[793] = -6; // obj_turnip
	global.__objectDepths[794] = -6; // obj_turnip_mini
	global.__objectDepths[795] = -6; // obj_turnip_large
	global.__objectDepths[796] = -6; // obj_turnip_bomb
	global.__objectDepths[797] = -6; // obj_turnip_shell
	global.__objectDepths[798] = -6; // obj_mblock_up
	global.__objectDepths[799] = -6; // obj_powblock_up
	global.__objectDepths[800] = -6; // obj_powblock_up_large
	global.__objectDepths[801] = -6; // obj_basket_up
	global.__objectDepths[802] = -6; // obj_basket_shard
	global.__objectDepths[803] = -6; // obj_basket_shard_bottom
	global.__objectDepths[804] = -2; // obj_iceblock
	global.__objectDepths[805] = 10000; // obj_explosion
	global.__objectDepths[806] = -11; // obj_dialog
	global.__objectDepths[807] = -11; // obj_message
	global.__objectDepths[808] = 0; // obj_firework_spawner
	global.__objectDepths[809] = 16; // obj_firework
	global.__objectDepths[810] = 17; // obj_firework_trail
	global.__objectDepths[811] = -6; // obj_score
	global.__objectDepths[812] = -6; // obj_score_flag
	global.__objectDepths[813] = 0; // obj_score_goal
	global.__objectDepths[814] = -6; // obj_score_coins
	global.__objectDepths[815] = 0; // obj_bubble
	global.__objectDepths[816] = -6; // obj_bubble_blown
	global.__objectDepths[817] = 0; // obj_bubble_v
	global.__objectDepths[818] = 0; // obj_lavaspark
	global.__objectDepths[819] = 10000; // obj_lightningsheet
	global.__objectDepths[820] = 10000; // obj_lightningsheet2
	global.__objectDepths[821] = -6; // obj_note
	global.__objectDepths[822] = -6; // obj_notespark
	global.__objectDepths[823] = -6; // obj_shellbump
	global.__objectDepths[824] = -6; // obj_spinsmoke
	global.__objectDepths[825] = -6; // obj_smoke
	global.__objectDepths[826] = -6; // obj_star
	global.__objectDepths[827] = -6; // obj_starspark
	global.__objectDepths[828] = -4; // obj_title
	global.__objectDepths[829] = -5; // obj_titlemenu
	global.__objectDepths[830] = -5; // obj_titlemenu_health
	global.__objectDepths[831] = -6; // obj_titlemenu_key
	global.__objectDepths[832] = -6; // obj_credits_text
	global.__objectDepths[833] = -12; // obj_savemenu
	global.__objectDepths[834] = -10; // obj_pausemenu
	global.__objectDepths[835] = -99; // obj_fadein
	global.__objectDepths[836] = -99; // obj_fadeout
	global.__objectDepths[837] = -99; // obj_curtainin
	global.__objectDepths[838] = -9; // obj_curtainout
	global.__objectDepths[839] = -9; // obj_foreground
	global.__objectDepths[840] = -11; // obj_hud
	global.__objectDepths[841] = -10; // obj_timeup
	global.__objectDepths[842] = 0; // obj_powkiller
	global.__objectDepths[843] = -6; // obj_dashkill
	global.__objectDepths[844] = -6; // obj_blockbumper
	global.__objectDepths[845] = 0; // obj_crystal_up
	global.__objectDepths[846] = 0; // obj_intro
	global.__objectDepths[847] = 1000000; // obj_credits
	global.__objectDepths[848] = 0; // obj_skipper
	global.__objectDepths[849] = -100; // obj_mariostart
	global.__objectDepths[850] = -5; // obj_gameover
	global.__objectDepths[851] = -2; // obj_up
	global.__objectDepths[852] = -2; // obj_down
	global.__objectDepths[853] = -2; // obj_left
	global.__objectDepths[854] = -2; // obj_right
	global.__objectDepths[855] = -2; // obj_endmarker


	global.__objectNames[0] = "obj_persistent";
	global.__objectNames[1] = "obj_rainmaker";
	global.__objectNames[2] = "obj_snowmaker";
	global.__objectNames[3] = "obj_discoball";
	global.__objectNames[4] = "obj_bganimator";
	global.__objectNames[5] = "obj_levelcontrol";
	global.__objectNames[6] = "obj_levelcontrol_light";
	global.__objectNames[7] = "obj_tilehider";
	global.__objectNames[8] = "obj_gotomap";
	global.__objectNames[9] = "obj_autoscroll";
	global.__objectNames[10] = "obj_autoscroll_modifier";
	global.__objectNames[11] = "obj_guessblock_manager";
	global.__objectNames[12] = "obj_light";
	global.__objectNames[13] = "obj_light_st";
	global.__objectNames[14] = "obj_light_disco";
	global.__objectNames[15] = "obj_player";
	global.__objectNames[16] = "obj_player_warp";
	global.__objectNames[17] = "obj_player_jump";
	global.__objectNames[18] = "obj_player_climb";
	global.__objectNames[19] = "obj_player_rocket";
	global.__objectNames[20] = "obj_solid";
	global.__objectNames[21] = "obj_semisolid";
	global.__objectNames[22] = "obj_climb";
	global.__objectNames[23] = "obj_climb_net";
	global.__objectNames[24] = "obj_swim";
	global.__objectNames[25] = "obj_slippery";
	global.__objectNames[26] = "obj_slope_r";
	global.__objectNames[27] = "obj_slope_l";
	global.__objectNames[28] = "obj_slope_sr";
	global.__objectNames[29] = "obj_slope_sl";
	global.__objectNames[30] = "obj_slope_ice_r";
	global.__objectNames[31] = "obj_slope_ice_l";
	global.__objectNames[32] = "obj_slope_ice_sr";
	global.__objectNames[33] = "obj_slope_ice_sl";
	global.__objectNames[34] = "obj_ceilslope_r";
	global.__objectNames[35] = "obj_ceilslope_l";
	global.__objectNames[36] = "obj_ceilslope_sr";
	global.__objectNames[37] = "obj_ceilslope_sl";
	global.__objectNames[38] = "obj_hurtmask";
	global.__objectNames[39] = "obj_hurtmask_square";
	global.__objectNames[40] = "obj_qblock";
	global.__objectNames[41] = "obj_qblock_scatter";
	global.__objectNames[42] = "obj_qblock_multicoin";
	global.__objectNames[43] = "obj_qblock_multicoin_shroom";
	global.__objectNames[44] = "obj_qblock_hidden";
	global.__objectNames[45] = "obj_qblock_double";
	global.__objectNames[46] = "obj_qblock_double_hidden";
	global.__objectNames[47] = "obj_qblock_triple";
	global.__objectNames[48] = "obj_qblock_triple_hidden";
	global.__objectNames[49] = "obj_qblock_big";
	global.__objectNames[50] = "obj_qblock_p";
	global.__objectNames[51] = "obj_qblock_spiked";
	global.__objectNames[52] = "obj_qblock_winged";
	global.__objectNames[53] = "obj_flowerblock";
	global.__objectNames[54] = "obj_leafblock";
	global.__objectNames[55] = "obj_hammerblock";
	global.__objectNames[56] = "obj_boomerangblock";
	global.__objectNames[57] = "obj_bombblock";
	global.__objectNames[58] = "obj_shellblock";
	global.__objectNames[59] = "obj_boltblock";
	global.__objectNames[60] = "obj_catblock";
	global.__objectNames[61] = "obj_starblock";
	global.__objectNames[62] = "obj_yoshiblock";
	global.__objectNames[63] = "obj_kuriboblock";
	global.__objectNames[64] = "obj_switchblock";
	global.__objectNames[65] = "obj_dashblock";
	global.__objectNames[66] = "obj_onoffblock_y";
	global.__objectNames[67] = "obj_onoffplatform_y";
	global.__objectNames[68] = "obj_onofflift_y";
	global.__objectNames[69] = "obj_onoffblock_g";
	global.__objectNames[70] = "obj_onoffplatform_g";
	global.__objectNames[71] = "obj_onofflift_g";
	global.__objectNames[72] = "obj_onoffblock_r";
	global.__objectNames[73] = "obj_onoffplatform_r";
	global.__objectNames[74] = "obj_onofflift_r";
	global.__objectNames[75] = "obj_onoffblock_b";
	global.__objectNames[76] = "obj_onoffplatform_b";
	global.__objectNames[77] = "obj_onofflift_b";
	global.__objectNames[78] = "obj_brick";
	global.__objectNames[79] = "obj_bigbrick";
	global.__objectNames[80] = "obj_bluebrick";
	global.__objectNames[81] = "obj_redbrick";
	global.__objectNames[82] = "obj_graybrick";
	global.__objectNames[83] = "obj_greenbrick";
	global.__objectNames[84] = "obj_flipblock";
	global.__objectNames[85] = "obj_viewblock";
	global.__objectNames[86] = "obj_noteblock";
	global.__objectNames[87] = "obj_noteblock_hidden";
	global.__objectNames[88] = "obj_noteblock_blue";
	global.__objectNames[89] = "obj_noteblock_blue_hidden";
	global.__objectNames[90] = "obj_noteblock_warp";
	global.__objectNames[91] = "obj_noteblock_warp_hidden";
	global.__objectNames[92] = "obj_noteblock_diagonal_r";
	global.__objectNames[93] = "obj_noteblock_diagonal_l";
	global.__objectNames[94] = "obj_messageblock";
	global.__objectNames[95] = "obj_pswitchblock";
	global.__objectNames[96] = "obj_qswitchblock";
	global.__objectNames[97] = "obj_eswitchblock";
	global.__objectNames[98] = "obj_woodblock";
	global.__objectNames[99] = "obj_eblock";
	global.__objectNames[100] = "obj_pblock";
	global.__objectNames[101] = "obj_area_y";
	global.__objectNames[102] = "obj_area_g";
	global.__objectNames[103] = "obj_area_r";
	global.__objectNames[104] = "obj_area_b";
	global.__objectNames[105] = "obj_arrowblock";
	global.__objectNames[106] = "obj_arrowblock_left";
	global.__objectNames[107] = "obj_arrowblock_right";
	global.__objectNames[108] = "obj_arrowblock_reset";
	global.__objectNames[109] = "obj_discoblock";
	global.__objectNames[110] = "obj_goomba";
	global.__objectNames[111] = "obj_paragoomba";
	global.__objectNames[112] = "obj_goombrat";
	global.__objectNames[113] = "obj_goomba_red";
	global.__objectNames[114] = "obj_paragoomba_red";
	global.__objectNames[115] = "obj_galoomba";
	global.__objectNames[116] = "obj_paragaloomba";
	global.__objectNames[117] = "obj_galoomba_parachute";
	global.__objectNames[118] = "obj_goombud";
	global.__objectNames[119] = "obj_goomba_shoe";
	global.__objectNames[120] = "obj_koopa";
	global.__objectNames[121] = "obj_parakoopa";
	global.__objectNames[122] = "obj_parakoopa_fly";
	global.__objectNames[123] = "obj_beachkoopa";
	global.__objectNames[124] = "obj_koopa_red";
	global.__objectNames[125] = "obj_parakoopa_red";
	global.__objectNames[126] = "obj_beachkoopa_red";
	global.__objectNames[127] = "obj_koopa_blue";
	global.__objectNames[128] = "obj_beachkoopa_blue";
	global.__objectNames[129] = "obj_koopa_yellow";
	global.__objectNames[130] = "obj_parakoopa_yellow";
	global.__objectNames[131] = "obj_beachkoopa_yellow";
	global.__objectNames[132] = "obj_rex";
	global.__objectNames[133] = "obj_rex_red";
	global.__objectNames[134] = "obj_dinotorch";
	global.__objectNames[135] = "obj_dinorhino";
	global.__objectNames[136] = "obj_spike";
	global.__objectNames[137] = "obj_buzzybeetle";
	global.__objectNames[138] = "obj_ceilingbuzzy";
	global.__objectNames[139] = "obj_spiny";
	global.__objectNames[140] = "obj_ceilingspiny";
	global.__objectNames[141] = "obj_pplant";
	global.__objectNames[142] = "obj_pplant_fire";
	global.__objectNames[143] = "obj_pplant_side_r";
	global.__objectNames[144] = "obj_pplant_side_l";
	global.__objectNames[145] = "obj_pplant_fire_side_r";
	global.__objectNames[146] = "obj_pplant_fire_side_l";
	global.__objectNames[147] = "obj_pplant_large";
	global.__objectNames[148] = "obj_pplant_large_down";
	global.__objectNames[149] = "obj_pplant_large_fire";
	global.__objectNames[150] = "obj_pplant_large_fire_down";
	global.__objectNames[151] = "obj_jpplant";
	global.__objectNames[152] = "obj_ptooie";
	global.__objectNames[153] = "obj_ptooie_pipe";
	global.__objectNames[154] = "obj_swooper";
	global.__objectNames[155] = "obj_spiketop";
	global.__objectNames[156] = "obj_spiketop_blue";
	global.__objectNames[157] = "obj_nokobomb";
	global.__objectNames[158] = "obj_nokobombette";
	global.__objectNames[159] = "obj_ceilingnokobombette";
	global.__objectNames[160] = "obj_blargg";
	global.__objectNames[161] = "obj_busterbeetle";
	global.__objectNames[162] = "obj_cheepcheep";
	global.__objectNames[163] = "obj_cheepcheep_jump";
	global.__objectNames[164] = "obj_cheepcheep_green";
	global.__objectNames[165] = "obj_smwcheep";
	global.__objectNames[166] = "obj_smwcheep_v";
	global.__objectNames[167] = "obj_smwcheep_flop";
	global.__objectNames[168] = "obj_bossbass";
	global.__objectNames[169] = "obj_bigbertha";
	global.__objectNames[170] = "obj_blurp";
	global.__objectNames[171] = "obj_ripvanfish";
	global.__objectNames[172] = "obj_porchupuffer";
	global.__objectNames[173] = "obj_urchin";
	global.__objectNames[174] = "obj_urchin_wall";
	global.__objectNames[175] = "obj_dolphin";
	global.__objectNames[176] = "obj_dolphin_jump";
	global.__objectNames[177] = "obj_lavalotus";
	global.__objectNames[178] = "obj_torpedobox";
	global.__objectNames[179] = "obj_jelectro";
	global.__objectNames[180] = "obj_blooper";
	global.__objectNames[181] = "obj_pokey";
	global.__objectNames[182] = "obj_firesnake";
	global.__objectNames[183] = "obj_brickgoomba";
	global.__objectNames[184] = "obj_angrysun";
	global.__objectNames[185] = "obj_hoopster";
	global.__objectNames[186] = "obj_ninji_black";
	global.__objectNames[187] = "obj_fuzzy";
	global.__objectNames[188] = "obj_fuzzy_line";
	global.__objectNames[189] = "obj_wiggler";
	global.__objectNames[190] = "obj_nipper";
	global.__objectNames[191] = "obj_firenipper";
	global.__objectNames[192] = "obj_monty";
	global.__objectNames[193] = "obj_monty_chase";
	global.__objectNames[194] = "obj_monty_dig";
	global.__objectNames[195] = "obj_volcanolotus";
	global.__objectNames[196] = "obj_lakitu";
	global.__objectNames[197] = "obj_lakitu_red";
	global.__objectNames[198] = "obj_pipelakitu";
	global.__objectNames[199] = "obj_pipelakitu_red";
	global.__objectNames[200] = "obj_firechomp";
	global.__objectNames[201] = "obj_parabeetle";
	global.__objectNames[202] = "obj_bigparabeetle";
	global.__objectNames[203] = "obj_foo";
	global.__objectNames[204] = "obj_skewer";
	global.__objectNames[205] = "obj_skewer_up";
	global.__objectNames[206] = "obj_skewer_left";
	global.__objectNames[207] = "obj_skewer_right";
	global.__objectNames[208] = "obj_firebar_manager";
	global.__objectNames[209] = "obj_rotodisc_manager";
	global.__objectNames[210] = "obj_ballnchain_manager";
	global.__objectNames[211] = "obj_laser_manager";
	global.__objectNames[212] = "obj_crusher";
	global.__objectNames[213] = "obj_pencilpillar";
	global.__objectNames[214] = "obj_drybones";
	global.__objectNames[215] = "obj_bonybeetle";
	global.__objectNames[216] = "obj_podoboo";
	global.__objectNames[217] = "obj_podoboo_ceiling";
	global.__objectNames[218] = "obj_thwomp";
	global.__objectNames[219] = "obj_thwomp_left";
	global.__objectNames[220] = "obj_thwomp_right";
	global.__objectNames[221] = "obj_thwomp_diagonal";
	global.__objectNames[222] = "obj_thwimp";
	global.__objectNames[223] = "obj_netkoopa";
	global.__objectNames[224] = "obj_netkoopa_red";
	global.__objectNames[225] = "obj_grinder";
	global.__objectNames[226] = "obj_grinder_line";
	global.__objectNames[227] = "obj_hotfoot";
	global.__objectNames[228] = "obj_lilspark";
	global.__objectNames[229] = "obj_hothead";
	global.__objectNames[230] = "obj_bowserstatue";
	global.__objectNames[231] = "obj_bowserstatue_gold";
	global.__objectNames[232] = "obj_magikoopa";
	global.__objectNames[233] = "obj_fishbone";
	global.__objectNames[234] = "obj_boo";
	global.__objectNames[235] = "obj_bigboo";
	global.__objectNames[236] = "obj_boocircle";
	global.__objectNames[237] = "obj_boosnake";
	global.__objectNames[238] = "obj_booblock";
	global.__objectNames[239] = "obj_boostretch";
	global.__objectNames[240] = "obj_boostretch_ceiling";
	global.__objectNames[241] = "obj_peepa_manager";
	global.__objectNames[242] = "obj_peepa";
	global.__objectNames[243] = "obj_peepa_v";
	global.__objectNames[244] = "obj_eerie";
	global.__objectNames[245] = "obj_bobomb";
	global.__objectNames[246] = "obj_bobomb_parachute";
	global.__objectNames[247] = "obj_mechakoopa";
	global.__objectNames[248] = "obj_bulletbill";
	global.__objectNames[249] = "obj_missilebill";
	global.__objectNames[250] = "obj_banzaibill";
	global.__objectNames[251] = "obj_banzaiblaster";
	global.__objectNames[252] = "obj_cannon";
	global.__objectNames[253] = "obj_cannon_side";
	global.__objectNames[254] = "obj_cannon_quad";
	global.__objectNames[255] = "obj_cannon_big";
	global.__objectNames[256] = "obj_cannon_spike";
	global.__objectNames[257] = "obj_engine";
	global.__objectNames[258] = "obj_engine_alt";
	global.__objectNames[259] = "obj_rockywrench";
	global.__objectNames[260] = "obj_shyguy";
	global.__objectNames[261] = "obj_shyguy_big";
	global.__objectNames[262] = "obj_shyguy_b";
	global.__objectNames[263] = "obj_shyguy_big_b";
	global.__objectNames[264] = "obj_shyguy_p";
	global.__objectNames[265] = "obj_snifit";
	global.__objectNames[266] = "obj_snifit_b";
	global.__objectNames[267] = "obj_snifit_g";
	global.__objectNames[268] = "obj_snifit_p";
	global.__objectNames[269] = "obj_ninji";
	global.__objectNames[270] = "obj_ninji_chase";
	global.__objectNames[271] = "obj_ninji_big";
	global.__objectNames[272] = "obj_tweeter";
	global.__objectNames[273] = "obj_tweeter_b";
	global.__objectNames[274] = "obj_hoopster_red";
	global.__objectNames[275] = "obj_bombguy";
	global.__objectNames[276] = "obj_cobrat";
	global.__objectNames[277] = "obj_cobrat_jar";
	global.__objectNames[278] = "obj_flurry";
	global.__objectNames[279] = "obj_beezo";
	global.__objectNames[280] = "obj_phanto";
	global.__objectNames[281] = "obj_panser";
	global.__objectNames[282] = "obj_panser_g";
	global.__objectNames[283] = "obj_panser_b";
	global.__objectNames[284] = "obj_panser_p";
	global.__objectNames[285] = "obj_pokey_green";
	global.__objectNames[286] = "obj_porcupo";
	global.__objectNames[287] = "obj_porcupo_r";
	global.__objectNames[288] = "obj_autobomb";
	global.__objectNames[289] = "obj_trouter";
	global.__objectNames[290] = "obj_goomba_big";
	global.__objectNames[291] = "obj_koopa_big";
	global.__objectNames[292] = "obj_parakoopa_big";
	global.__objectNames[293] = "obj_parakoopa_big_fly";
	global.__objectNames[294] = "obj_koopa_big_red";
	global.__objectNames[295] = "obj_parakoopa_big_red";
	global.__objectNames[296] = "obj_bigplant";
	global.__objectNames[297] = "obj_megamole";
	global.__objectNames[298] = "obj_bossorb";
	global.__objectNames[299] = "obj_bossdoor";
	global.__objectNames[300] = "obj_boomboom";
	global.__objectNames[301] = "obj_generator_galoomba";
	global.__objectNames[302] = "obj_generator_cheepcheep";
	global.__objectNames[303] = "obj_generator_spikedcheep";
	global.__objectNames[304] = "obj_generator_spikedcheep_b";
	global.__objectNames[305] = "obj_generator_dolphin";
	global.__objectNames[306] = "obj_generator_eerie";
	global.__objectNames[307] = "obj_generator_bobomb";
	global.__objectNames[308] = "obj_generator_bulletbill";
	global.__objectNames[309] = "obj_generator_beezo";
	global.__objectNames[310] = "obj_generator_enemy";
	global.__objectNames[311] = "obj_hammerbro";
	global.__objectNames[312] = "obj_boomerangbro";
	global.__objectNames[313] = "obj_firebro";
	global.__objectNames[314] = "obj_icebro";
	global.__objectNames[315] = "obj_sledgebro";
	global.__objectNames[316] = "obj_afhb";
	global.__objectNames[317] = "obj_sumobro";
	global.__objectNames[318] = "obj_walrus";
	global.__objectNames[319] = "obj_pararus";
	global.__objectNames[320] = "obj_grayrus";
	global.__objectNames[321] = "obj_gladrus";
	global.__objectNames[322] = "obj_chainchomp";
	global.__objectNames[323] = "obj_charginchuck";
	global.__objectNames[324] = "obj_clappinchuck";
	global.__objectNames[325] = "obj_holdbubble_enemy";
	global.__objectNames[326] = "obj_mapcontrol";
	global.__objectNames[327] = "obj_mapplayer";
	global.__objectNames[328] = "obj_mapbridge_h";
	global.__objectNames[329] = "obj_mapbridge_v";
	global.__objectNames[330] = "obj_mappath_ladder";
	global.__objectNames[331] = "obj_mappath_beanstalk";
	global.__objectNames[332] = "obj_mappath_h";
	global.__objectNames[333] = "obj_mappath_v";
	global.__objectNames[334] = "obj_mappath_up";
	global.__objectNames[335] = "obj_mappath_down";
	global.__objectNames[336] = "obj_mappath_left";
	global.__objectNames[337] = "obj_mappath_right";
	global.__objectNames[338] = "obj_mappath_upleft";
	global.__objectNames[339] = "obj_mappath_upright";
	global.__objectNames[340] = "obj_mappath_downleft";
	global.__objectNames[341] = "obj_mappath_downright";
	global.__objectNames[342] = "obj_mappath_levelnode";
	global.__objectNames[343] = "obj_mappath_emptynode";
	global.__objectNames[344] = "obj_mappath_water";
	global.__objectNames[345] = "obj_maplevel_switch_y";
	global.__objectNames[346] = "obj_maplevel_switch_g";
	global.__objectNames[347] = "obj_maplevel_switch_r";
	global.__objectNames[348] = "obj_maplevel_switch_b";
	global.__objectNames[349] = "obj_mappanel_house";
	global.__objectNames[350] = "obj_mappanel_house_b";
	global.__objectNames[351] = "obj_mappanel_house_c";
	global.__objectNames[352] = "obj_mapstart";
	global.__objectNames[353] = "obj_maplevel";
	global.__objectNames[354] = "obj_maplevel_pipe";
	global.__objectNames[355] = "obj_maplevel_pipe2";
	global.__objectNames[356] = "obj_maplevel_ghost";
	global.__objectNames[357] = "obj_maplevel_castle";
	global.__objectNames[358] = "obj_mapwater";
	global.__objectNames[359] = "obj_maplava";
	global.__objectNames[360] = "obj_maptree";
	global.__objectNames[361] = "obj_maptree_alt";
	global.__objectNames[362] = "obj_maptree_alt_b";
	global.__objectNames[363] = "obj_maphill";
	global.__objectNames[364] = "obj_maphilltrio";
	global.__objectNames[365] = "obj_mapfire";
	global.__objectNames[366] = "obj_modifier";
	global.__objectNames[367] = "obj_modifier_music";
	global.__objectNames[368] = "obj_muncher";
	global.__objectNames[369] = "obj_muncher_pipe";
	global.__objectNames[370] = "obj_muncher_pipe2";
	global.__objectNames[371] = "obj_watertop";
	global.__objectNames[372] = "obj_waterfall";
	global.__objectNames[373] = "obj_waterfall_noswim";
	global.__objectNames[374] = "obj_tides";
	global.__objectNames[375] = "obj_ilavaslope_l";
	global.__objectNames[376] = "obj_ilavaslope_r";
	global.__objectNames[377] = "obj_ilavaslope_sl";
	global.__objectNames[378] = "obj_ilavaslope_sr";
	global.__objectNames[379] = "obj_lavacorner_a";
	global.__objectNames[380] = "obj_lavacorner_b";
	global.__objectNames[381] = "obj_lavacorner_c";
	global.__objectNames[382] = "obj_lavacorner_d";
	global.__objectNames[383] = "obj_lavaedge_a";
	global.__objectNames[384] = "obj_lavaedge_b";
	global.__objectNames[385] = "obj_lavaedge_c";
	global.__objectNames[386] = "obj_lavaedge_d";
	global.__objectNames[387] = "obj_lavaslope_l";
	global.__objectNames[388] = "obj_lavaslope_r";
	global.__objectNames[389] = "obj_lavaslope_sl";
	global.__objectNames[390] = "obj_lavaslope_sr";
	global.__objectNames[391] = "obj_lava_top";
	global.__objectNames[392] = "obj_lava_ceiling";
	global.__objectNames[393] = "obj_lava";
	global.__objectNames[394] = "obj_lava_b";
	global.__objectNames[395] = "obj_lava_c";
	global.__objectNames[396] = "obj_lava_d";
	global.__objectNames[397] = "obj_lavafall";
	global.__objectNames[398] = "obj_vine";
	global.__objectNames[399] = "obj_signpost";
	global.__objectNames[400] = "obj_seaweed";
	global.__objectNames[401] = "obj_quicksand";
	global.__objectNames[402] = "obj_mushroom";
	global.__objectNames[403] = "obj_fireflower";
	global.__objectNames[404] = "obj_iceflower";
	global.__objectNames[405] = "obj_carrot";
	global.__objectNames[406] = "obj_leaf";
	global.__objectNames[407] = "obj_frogsuit";
	global.__objectNames[408] = "obj_tanookisuit";
	global.__objectNames[409] = "obj_hammerflower";
	global.__objectNames[410] = "obj_boomerangflower";
	global.__objectNames[411] = "obj_superflower";
	global.__objectNames[412] = "obj_bombshroom";
	global.__objectNames[413] = "obj_blueshell";
	global.__objectNames[414] = "obj_beeshroom";
	global.__objectNames[415] = "obj_voltshroom";
	global.__objectNames[416] = "obj_penguinsuit";
	global.__objectNames[417] = "obj_propellershroom";
	global.__objectNames[418] = "obj_superbell";
	global.__objectNames[419] = "obj_helmet";
	global.__objectNames[420] = "obj_starman";
	global.__objectNames[421] = "obj_pwing";
	global.__objectNames[422] = "obj_1up";
	global.__objectNames[423] = "obj_poison";
	global.__objectNames[424] = "obj_rotten";
	global.__objectNames[425] = "obj_goldshroom";
	global.__objectNames[426] = "obj_1up_h1";
	global.__objectNames[427] = "obj_1up_h2";
	global.__objectNames[428] = "obj_1up_h3";
	global.__objectNames[429] = "obj_1up_h4";
	global.__objectNames[430] = "obj_redring";
	global.__objectNames[431] = "obj_yellowring";
	global.__objectNames[432] = "obj_coin";
	global.__objectNames[433] = "obj_coin_p";
	global.__objectNames[434] = "obj_coin_r";
	global.__objectNames[435] = "obj_acecoin";
	global.__objectNames[436] = "obj_starcoin";
	global.__objectNames[437] = "obj_berry";
	global.__objectNames[438] = "obj_berry_g";
	global.__objectNames[439] = "obj_holdbubble";
	global.__objectNames[440] = "obj_plusclock_10";
	global.__objectNames[441] = "obj_plusclock_50";
	global.__objectNames[442] = "obj_icecoin";
	global.__objectNames[443] = "obj_iceplant";
	global.__objectNames[444] = "obj_3upmoon";
	global.__objectNames[445] = "obj_path";
	global.__objectNames[446] = "obj_path_hor";
	global.__objectNames[447] = "obj_path_ver";
	global.__objectNames[448] = "obj_path_diagonal_r";
	global.__objectNames[449] = "obj_path_diagonal_l";
	global.__objectNames[450] = "obj_path_circle_a1";
	global.__objectNames[451] = "obj_path_circle_a2";
	global.__objectNames[452] = "obj_path_circle_a3";
	global.__objectNames[453] = "obj_path_circle_a4";
	global.__objectNames[454] = "obj_path_circle_b1";
	global.__objectNames[455] = "obj_path_circle_b2";
	global.__objectNames[456] = "obj_path_circle_b3";
	global.__objectNames[457] = "obj_path_circle_b4";
	global.__objectNames[458] = "obj_platform";
	global.__objectNames[459] = "obj_platform_touch";
	global.__objectNames[460] = "obj_platform_floating";
	global.__objectNames[461] = "obj_platform_falling";
	global.__objectNames[462] = "obj_generator_log";
	global.__objectNames[463] = "obj_carrotlift";
	global.__objectNames[464] = "obj_carrotlift_32x";
	global.__objectNames[465] = "obj_arrowplatform";
	global.__objectNames[466] = "obj_rotaryplatform";
	global.__objectNames[467] = "obj_boltlift";
	global.__objectNames[468] = "obj_donut";
	global.__objectNames[469] = "obj_donut_triple";
	global.__objectNames[470] = "obj_donut_red";
	global.__objectNames[471] = "obj_donut_red_triple";
	global.__objectNames[472] = "obj_ferrisplatform";
	global.__objectNames[473] = "obj_ferrisplatform_2x";
	global.__objectNames[474] = "obj_ferrisplatform_3x";
	global.__objectNames[475] = "obj_balanceplatform";
	global.__objectNames[476] = "obj_accordion_h";
	global.__objectNames[477] = "obj_accordion_v";
	global.__objectNames[478] = "obj_accordion_hv";
	global.__objectNames[479] = "obj_blocktrain";
	global.__objectNames[480] = "obj_stoneblock";
	global.__objectNames[481] = "obj_timedplatform";
	global.__objectNames[482] = "obj_slopeplatform_r";
	global.__objectNames[483] = "obj_slopeplatform_l";
	global.__objectNames[484] = "obj_weightplatform";
	global.__objectNames[485] = "obj_movingrope";
	global.__objectNames[486] = "obj_movingsaw";
	global.__objectNames[487] = "obj_movingpipe";
	global.__objectNames[488] = "obj_skullraft";
	global.__objectNames[489] = "obj_conveyor_l";
	global.__objectNames[490] = "obj_conveyor_r";
	global.__objectNames[491] = "obj_yoshiplatform";
	global.__objectNames[492] = "obj_pulleyplatform";
	global.__objectNames[493] = "obj_mushroomplatform";
	global.__objectNames[494] = "obj_jellyplatform";
	global.__objectNames[495] = "obj_flagpole";
	global.__objectNames[496] = "obj_flagpole_secret";
	global.__objectNames[497] = "obj_incastle";
	global.__objectNames[498] = "obj_crystal";
	global.__objectNames[499] = "obj_crystal_red";
	global.__objectNames[500] = "obj_hawkmouth";
	global.__objectNames[501] = "obj_hawkmouth_secret";
	global.__objectNames[502] = "obj_goalcard";
	global.__objectNames[503] = "obj_goalcard_secret";
	global.__objectNames[504] = "obj_goalgate";
	global.__objectNames[505] = "obj_goalgate_secret";
	global.__objectNames[506] = "obj_keyhole";
	global.__objectNames[507] = "obj_checkpoint";
	global.__objectNames[508] = "obj_midwaygate";
	global.__objectNames[509] = "obj_midwaygate_tape";
	global.__objectNames[510] = "obj_pswitch";
	global.__objectNames[511] = "obj_gswitch";
	global.__objectNames[512] = "obj_trampoline";
	global.__objectNames[513] = "obj_trampoline_p";
	global.__objectNames[514] = "obj_trampoline_timed";
	global.__objectNames[515] = "obj_barrel";
	global.__objectNames[516] = "obj_barrel_tnt";
	global.__objectNames[517] = "obj_billygun";
	global.__objectNames[518] = "obj_pipeypipe";
	global.__objectNames[519] = "obj_bumper";
	global.__objectNames[520] = "obj_wallspring";
	global.__objectNames[521] = "obj_flipper_top";
	global.__objectNames[522] = "obj_flipper_bottom";
	global.__objectNames[523] = "obj_flipper_left";
	global.__objectNames[524] = "obj_flipper_right";
	global.__objectNames[525] = "obj_blowpipe";
	global.__objectNames[526] = "obj_walltriangle_r";
	global.__objectNames[527] = "obj_walltriangle_l";
	global.__objectNames[528] = "obj_walltriangle_ir";
	global.__objectNames[529] = "obj_walltriangle_il";
	global.__objectNames[530] = "obj_lightblock";
	global.__objectNames[531] = "obj_propellerblock";
	global.__objectNames[532] = "obj_boomerang_blue";
	global.__objectNames[533] = "obj_waterbubble";
	global.__objectNames[534] = "obj_twister";
	global.__objectNames[535] = "obj_pullkey";
	global.__objectNames[536] = "obj_heart";
	global.__objectNames[537] = "obj_cherry";
	global.__objectNames[538] = "obj_vegshroom";
	global.__objectNames[539] = "obj_vegshroom_1up";
	global.__objectNames[540] = "obj_basket";
	global.__objectNames[541] = "obj_grass_coin";
	global.__objectNames[542] = "obj_grass_multicoin";
	global.__objectNames[543] = "obj_grass_sprout";
	global.__objectNames[544] = "obj_grass_pow";
	global.__objectNames[545] = "obj_grass_pow_large";
	global.__objectNames[546] = "obj_grass_bomb";
	global.__objectNames[547] = "obj_grass_shell";
	global.__objectNames[548] = "obj_grass";
	global.__objectNames[549] = "obj_grass_mini";
	global.__objectNames[550] = "obj_grass_large";
	global.__objectNames[551] = "obj_grass_rocket";
	global.__objectNames[552] = "obj_mblock";
	global.__objectNames[553] = "obj_powblock";
	global.__objectNames[554] = "obj_itembubble";
	global.__objectNames[555] = "obj_digsand";
	global.__objectNames[556] = "obj_key";
	global.__objectNames[557] = "obj_key_timed";
	global.__objectNames[558] = "obj_keygate";
	global.__objectNames[559] = "obj_door";
	global.__objectNames[560] = "obj_door_p";
	global.__objectNames[561] = "obj_pipecorner_dr";
	global.__objectNames[562] = "obj_pipecorner_dl";
	global.__objectNames[563] = "obj_pipecorner_ur";
	global.__objectNames[564] = "obj_pipecorner_ul";
	global.__objectNames[565] = "obj_warptop";
	global.__objectNames[566] = "obj_warpbottom";
	global.__objectNames[567] = "obj_warpleft";
	global.__objectNames[568] = "obj_warpright";
	global.__objectNames[569] = "obj_warpmap";
	global.__objectNames[570] = "obj_warppost";
	global.__objectNames[571] = "obj_warproom";
	global.__objectNames[572] = "obj_warpbranch";
	global.__objectNames[573] = "obj_warpcannon";
	global.__objectNames[574] = "obj_warpcannon_big";
	global.__objectNames[575] = "obj_pitwarp";
	global.__objectNames[576] = "obj_pipemanager";
	global.__objectNames[577] = "obj_diggame_block";
	global.__objectNames[578] = "obj_diggame_chest";
	global.__objectNames[579] = "obj_diggame_warptomap";
	global.__objectNames[580] = "obj_toad_slot";
	global.__objectNames[581] = "obj_slotblock";
	global.__objectNames[582] = "obj_slotblock_manager";
	global.__objectNames[583] = "obj_toad";
	global.__objectNames[584] = "obj_chest";
	global.__objectNames[585] = "obj_palacemsg";
	global.__objectNames[586] = "obj_palaceswitch";
	global.__objectNames[587] = "obj_parpull";
	global.__objectNames[588] = "obj_parcarry";
	global.__objectNames[589] = "obj_parhold";
	global.__objectNames[590] = "obj_enemyparent";
	global.__objectNames[591] = "obj_enemyparent_held";
	global.__objectNames[592] = "obj_deactenemyparent";
	global.__objectNames[593] = "obj_subconenemyparent";
	global.__objectNames[594] = "obj_bossparent";
	global.__objectNames[595] = "obj_physicsparent";
	global.__objectNames[596] = "obj_powerupparent";
	global.__objectNames[597] = "obj_projectileparent";
	global.__objectNames[598] = "obj_playerparent";
	global.__objectNames[599] = "obj_playerparent_clear";
	global.__objectNames[600] = "obj_enemytop";
	global.__objectNames[601] = "obj_platformparent";
	global.__objectNames[602] = "obj_slopeparent";
	global.__objectNames[603] = "obj_ceilslopeparent";
	global.__objectNames[604] = "obj_mappathparent";
	global.__objectNames[605] = "obj_maplevelparent";
	global.__objectNames[606] = "obj_pathparent";
	global.__objectNames[607] = "obj_blockparent";
	global.__objectNames[608] = "obj_grayblockparent";
	global.__objectNames[609] = "obj_lightparent";
	global.__objectNames[610] = "obj_deactivateparent";
	global.__objectNames[611] = "obj_mario";
	global.__objectNames[612] = "obj_player_goal_smb1";
	global.__objectNames[613] = "obj_player_goal_smb2";
	global.__objectNames[614] = "obj_player_goal_smb3";
	global.__objectNames[615] = "obj_player_goal_smw";
	global.__objectNames[616] = "obj_player_warpnote";
	global.__objectNames[617] = "obj_player_transform";
	global.__objectNames[618] = "obj_player_rocket2";
	global.__objectNames[619] = "obj_player_eaten";
	global.__objectNames[620] = "obj_player_dead";
	global.__objectNames[621] = "obj_player_door";
	global.__objectNames[622] = "obj_puller";
	global.__objectNames[623] = "obj_statue";
	global.__objectNames[624] = "obj_spinner";
	global.__objectNames[625] = "obj_dropdown";
	global.__objectNames[626] = "obj_wallrunner";
	global.__objectNames[627] = "obj_marker_head";
	global.__objectNames[628] = "obj_marker_bottom";
	global.__objectNames[629] = "obj_emptyblock";
	global.__objectNames[630] = "obj_blockcoin";
	global.__objectNames[631] = "obj_blockcoin2";
	global.__objectNames[632] = "obj_beanstalk";
	global.__objectNames[633] = "obj_bluebrick_th";
	global.__objectNames[634] = "obj_flipblock_flip";
	global.__objectNames[635] = "obj_shard";
	global.__objectNames[636] = "obj_shard_th";
	global.__objectNames[637] = "obj_shard_switch";
	global.__objectNames[638] = "obj_guessblock";
	global.__objectNames[639] = "obj_enemy_dead";
	global.__objectNames[640] = "obj_enemy_multidead";
	global.__objectNames[641] = "obj_enemy_stomped";
	global.__objectNames[642] = "obj_enemy_carried";
	global.__objectNames[643] = "obj_enemy_tick";
	global.__objectNames[644] = "obj_enemy_coin";
	global.__objectNames[645] = "obj_enemy_score";
	global.__objectNames[646] = "obj_stomped";
	global.__objectNames[647] = "obj_goomba_micro";
	global.__objectNames[648] = "obj_galoomba_down";
	global.__objectNames[649] = "obj_koopa_kamikaze";
	global.__objectNames[650] = "obj_dinotorch_fire";
	global.__objectNames[651] = "obj_spike_ball";
	global.__objectNames[652] = "obj_plantfire";
	global.__objectNames[653] = "obj_plantfire2";
	global.__objectNames[654] = "obj_plantball";
	global.__objectNames[655] = "obj_nokobomb_down";
	global.__objectNames[656] = "obj_blargg_jump";
	global.__objectNames[657] = "obj_busterpickup";
	global.__objectNames[658] = "obj_generatorcheep";
	global.__objectNames[659] = "obj_generatorcheep2";
	global.__objectNames[660] = "obj_generatorcheep2b";
	global.__objectNames[661] = "obj_bigbertha_cheep";
	global.__objectNames[662] = "obj_generatordolphin";
	global.__objectNames[663] = "obj_lavalotus_ball";
	global.__objectNames[664] = "obj_torpedoted";
	global.__objectNames[665] = "obj_pokey_dead";
	global.__objectNames[666] = "obj_monty_jump";
	global.__objectNames[667] = "obj_lotusball";
	global.__objectNames[668] = "obj_firesnake_body";
	global.__objectNames[669] = "obj_angrysun_movement";
	global.__objectNames[670] = "obj_wiggler_body";
	global.__objectNames[671] = "obj_lakitu_movement";
	global.__objectNames[672] = "obj_lakitu_egg";
	global.__objectNames[673] = "obj_firechomp_fire";
	global.__objectNames[674] = "obj_foo_fog";
	global.__objectNames[675] = "obj_skewer_trunk";
	global.__objectNames[676] = "obj_skewer_trunk_up";
	global.__objectNames[677] = "obj_skewer_trunk_left";
	global.__objectNames[678] = "obj_skewer_trunk_right";
	global.__objectNames[679] = "obj_firebar";
	global.__objectNames[680] = "obj_rotodisc";
	global.__objectNames[681] = "obj_rotodisc_trail";
	global.__objectNames[682] = "obj_chain";
	global.__objectNames[683] = "obj_ball";
	global.__objectNames[684] = "obj_laser";
	global.__objectNames[685] = "obj_crumblebones";
	global.__objectNames[686] = "obj_boocircle_boo";
	global.__objectNames[687] = "obj_boosnake_trail";
	global.__objectNames[688] = "obj_peepa_b";
	global.__objectNames[689] = "obj_eerie_active";
	global.__objectNames[690] = "obj_bowserstatue_fire";
	global.__objectNames[691] = "obj_magic";
	global.__objectNames[692] = "obj_bobomb_down";
	global.__objectNames[693] = "obj_mechakoopa_down";
	global.__objectNames[694] = "obj_bullet";
	global.__objectNames[695] = "obj_bullet_homing";
	global.__objectNames[696] = "obj_bullet_banzai";
	global.__objectNames[697] = "obj_cannonball";
	global.__objectNames[698] = "obj_cannonball_large";
	global.__objectNames[699] = "obj_cannonball_spike";
	global.__objectNames[700] = "obj_cannonball_spike_trail";
	global.__objectNames[701] = "obj_wrench";
	global.__objectNames[702] = "obj_snifit_ball";
	global.__objectNames[703] = "obj_beezo_active";
	global.__objectNames[704] = "obj_panser_fire";
	global.__objectNames[705] = "obj_autobomb_shyguy";
	global.__objectNames[706] = "obj_autobomb_fire";
	global.__objectNames[707] = "obj_shell";
	global.__objectNames[708] = "obj_shell_kick";
	global.__objectNames[709] = "obj_hammerbro_hammer";
	global.__objectNames[710] = "obj_boomerangbro_boomerang";
	global.__objectNames[711] = "obj_firebro_fireball";
	global.__objectNames[712] = "obj_icebro_snowball";
	global.__objectNames[713] = "obj_afhb_rider";
	global.__objectNames[714] = "obj_sumobro_flame";
	global.__objectNames[715] = "obj_sumobro_lightning";
	global.__objectNames[716] = "obj_chomp";
	global.__objectNames[717] = "obj_chomp_chain";
	global.__objectNames[718] = "obj_holdbubble_enemy_respawn";
	global.__objectNames[719] = "obj_mapghost";
	global.__objectNames[720] = "obj_opener";
	global.__objectNames[721] = "obj_mapcloud";
	global.__objectNames[722] = "obj_coin_m";
	global.__objectNames[723] = "obj_pickup_leaf";
	global.__objectNames[724] = "obj_pickup_pwing";
	global.__objectNames[725] = "obj_pickup_propeller";
	global.__objectNames[726] = "obj_egg";
	global.__objectNames[727] = "obj_egg_pow";
	global.__objectNames[728] = "obj_egg_hatch";
	global.__objectNames[729] = "obj_yoshi";
	global.__objectNames[730] = "obj_yoshi_runaway";
	global.__objectNames[731] = "obj_yoshi_abandon";
	global.__objectNames[732] = "obj_yoshi_fire";
	global.__objectNames[733] = "obj_tongue";
	global.__objectNames[734] = "obj_getshoe";
	global.__objectNames[735] = "obj_kuriboshoe";
	global.__objectNames[736] = "obj_kuriboshoe_lost";
	global.__objectNames[737] = "obj_kuriboshoe_movement";
	global.__objectNames[738] = "obj_stomp";
	global.__objectNames[739] = "obj_powerupsprout";
	global.__objectNames[740] = "obj_powerupprize";
	global.__objectNames[741] = "obj_powerupget";
	global.__objectNames[742] = "obj_reserveitem";
	global.__objectNames[743] = "obj_fireball";
	global.__objectNames[744] = "obj_iceball";
	global.__objectNames[745] = "obj_hammer";
	global.__objectNames[746] = "obj_boomerang";
	global.__objectNames[747] = "obj_superball";
	global.__objectNames[748] = "obj_bomb";
	global.__objectNames[749] = "obj_bolt";
	global.__objectNames[750] = "obj_football";
	global.__objectNames[751] = "obj_invincibility";
	global.__objectNames[752] = "obj_coinchange";
	global.__objectNames[753] = "obj_holdbubble_respawn";
	global.__objectNames[754] = "obj_log";
	global.__objectNames[755] = "obj_arrowplatform_platform";
	global.__objectNames[756] = "obj_spinmask";
	global.__objectNames[757] = "obj_spincollision";
	global.__objectNames[758] = "obj_boltlift_top";
	global.__objectNames[759] = "obj_boltlift_fall";
	global.__objectNames[760] = "obj_ferrisplatform_platform";
	global.__objectNames[761] = "obj_balanceplatform_platform";
	global.__objectNames[762] = "obj_expandplatblock";
	global.__objectNames[763] = "obj_blocktrain_front";
	global.__objectNames[764] = "obj_blocktrain_middle";
	global.__objectNames[765] = "obj_blocktrain_back";
	global.__objectNames[766] = "obj_blocktrain_killer";
	global.__objectNames[767] = "obj_weightplatform_right";
	global.__objectNames[768] = "obj_rope";
	global.__objectNames[769] = "obj_saw";
	global.__objectNames[770] = "obj_pulleyplatform_right";
	global.__objectNames[771] = "obj_pulleyplatform_rope";
	global.__objectNames[772] = "obj_flag";
	global.__objectNames[773] = "obj_flag_p";
	global.__objectNames[774] = "obj_flag_da";
	global.__objectNames[775] = "obj_goalcard_get";
	global.__objectNames[776] = "obj_fadegoal";
	global.__objectNames[777] = "obj_curtaingoal";
	global.__objectNames[778] = "obj_goalgate_tape";
	global.__objectNames[779] = "obj_goalgate_tape_b";
	global.__objectNames[780] = "obj_goalgate_front";
	global.__objectNames[781] = "obj_midwaygate_b";
	global.__objectNames[782] = "obj_trampoline_p_active";
	global.__objectNames[783] = "obj_barrel_up";
	global.__objectNames[784] = "obj_billy";
	global.__objectNames[785] = "obj_billy_dead";
	global.__objectNames[786] = "obj_pipeypipe_plant";
	global.__objectNames[787] = "obj_propellerblock_up";
	global.__objectNames[788] = "obj_boomerang_blue_up";
	global.__objectNames[789] = "obj_twister_bubble";
	global.__objectNames[790] = "obj_turnip_out";
	global.__objectNames[791] = "obj_sorcerer";
	global.__objectNames[792] = "obj_pullkey_up";
	global.__objectNames[793] = "obj_turnip";
	global.__objectNames[794] = "obj_turnip_mini";
	global.__objectNames[795] = "obj_turnip_large";
	global.__objectNames[796] = "obj_turnip_bomb";
	global.__objectNames[797] = "obj_turnip_shell";
	global.__objectNames[798] = "obj_mblock_up";
	global.__objectNames[799] = "obj_powblock_up";
	global.__objectNames[800] = "obj_powblock_up_large";
	global.__objectNames[801] = "obj_basket_up";
	global.__objectNames[802] = "obj_basket_shard";
	global.__objectNames[803] = "obj_basket_shard_bottom";
	global.__objectNames[804] = "obj_iceblock";
	global.__objectNames[805] = "obj_explosion";
	global.__objectNames[806] = "obj_dialog";
	global.__objectNames[807] = "obj_message";
	global.__objectNames[808] = "obj_firework_spawner";
	global.__objectNames[809] = "obj_firework";
	global.__objectNames[810] = "obj_firework_trail";
	global.__objectNames[811] = "obj_score";
	global.__objectNames[812] = "obj_score_flag";
	global.__objectNames[813] = "obj_score_goal";
	global.__objectNames[814] = "obj_score_coins";
	global.__objectNames[815] = "obj_bubble";
	global.__objectNames[816] = "obj_bubble_blown";
	global.__objectNames[817] = "obj_bubble_v";
	global.__objectNames[818] = "obj_lavaspark";
	global.__objectNames[819] = "obj_lightningsheet";
	global.__objectNames[820] = "obj_lightningsheet2";
	global.__objectNames[821] = "obj_note";
	global.__objectNames[822] = "obj_notespark";
	global.__objectNames[823] = "obj_shellbump";
	global.__objectNames[824] = "obj_spinsmoke";
	global.__objectNames[825] = "obj_smoke";
	global.__objectNames[826] = "obj_star";
	global.__objectNames[827] = "obj_starspark";
	global.__objectNames[828] = "obj_title";
	global.__objectNames[829] = "obj_titlemenu";
	global.__objectNames[830] = "obj_titlemenu_health";
	global.__objectNames[831] = "obj_titlemenu_key";
	global.__objectNames[832] = "obj_credits_text";
	global.__objectNames[833] = "obj_savemenu";
	global.__objectNames[834] = "obj_pausemenu";
	global.__objectNames[835] = "obj_fadein";
	global.__objectNames[836] = "obj_fadeout";
	global.__objectNames[837] = "obj_curtainin";
	global.__objectNames[838] = "obj_curtainout";
	global.__objectNames[839] = "obj_foreground";
	global.__objectNames[840] = "obj_hud";
	global.__objectNames[841] = "obj_timeup";
	global.__objectNames[842] = "obj_powkiller";
	global.__objectNames[843] = "obj_dashkill";
	global.__objectNames[844] = "obj_blockbumper";
	global.__objectNames[845] = "obj_crystal_up";
	global.__objectNames[846] = "obj_intro";
	global.__objectNames[847] = "obj_credits";
	global.__objectNames[848] = "obj_skipper";
	global.__objectNames[849] = "obj_mariostart";
	global.__objectNames[850] = "obj_gameover";
	global.__objectNames[851] = "obj_up";
	global.__objectNames[852] = "obj_down";
	global.__objectNames[853] = "obj_left";
	global.__objectNames[854] = "obj_right";
	global.__objectNames[855] = "obj_endmarker";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
